In [1]:
from datasets import load_dataset

DATASET_NAME = "rescommons/Full-Ecom-Chatbot-Dataset"

dataset = load_dataset(DATASET_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/5.48k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 19.9MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 5.03MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/35213 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/8818 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'source', 'group', 'difficulty', 'system', 'history', 'prompt', 'context', 'tools', 'response_type', 'response', 'language', 'locale', 'annotator', 'quality_score', 'domain', 'intent_category', 'intent', 'sub_intent', 'capability', 'test_tier'],
        num_rows: 35213
    })
    test: Dataset({
        features: ['id', 'source', 'group', 'difficulty', 'system', 'history', 'prompt', 'context', 'tools', 'response_type', 'response', 'language', 'locale', 'annotator', 'quality_score', 'domain', 'intent_category', 'intent', 'sub_intent', 'capability', 'test_tier'],
        num_rows: 8818
    })
})

In [ ]:
dataset.items()

dict_items([('train', Dataset({
    features: ['id', 'source', 'group', 'difficulty', 'system', 'history', 'prompt', 'context', 'tools', 'response_type', 'response', 'language', 'locale', 'annotator', 'quality_score', 'domain', 'intent_category', 'intent', 'sub_intent', 'capability', 'test_tier'],
    num_rows: 35213
})), ('test', Dataset({
    features: ['id', 'source', 'group', 'difficulty', 'system', 'history', 'prompt', 'context', 'tools', 'response_type', 'response', 'language', 'locale', 'annotator', 'quality_score', 'domain', 'intent_category', 'intent', 'sub_intent', 'capability', 'test_tier'],
    num_rows: 8818
}))])

In [ ]:
for feature_name, feature in dataset["train"].features.items():
    print(f"{feature_name:20} -> {feature}")

id                   -> Value('large_string')
source               -> Value('large_string')
group                -> Value('large_string')
difficulty           -> Value('int64')
system               -> Value('large_string')
history              -> Value('large_string')
prompt               -> Value('large_string')
context              -> Value('large_string')
tools                -> Value('large_string')
response_type        -> Value('large_string')
response             -> Value('large_string')
language             -> Value('large_string')
locale               -> Value('large_string')
annotator            -> Value('large_string')
quality_score        -> Value('float64')
domain               -> Value('large_string')
intent_category      -> Value('large_string')
intent               -> Value('large_string')
sub_intent           -> Value('large_string')
capability           -> Value('large_string')
test_tier            -> Value('large_string')

In [ ]:
for column in ["system", "history", "context", "tools", "response"]:
    print(f"\n{'=' * 80}")
    print(f"{column.upper()}")
    print("=" * 80)

    for i in range(5):
        print(f"\n--- Sample {i} ---")
        print(dataset["train"][i][column])

================================================================================
SYSTEM
================================================================================

--- Sample 0 ---
You are Aria, a helpful e-commerce assistant. You help customers search for products, track orders, manage returns, answer questions, and resolve issues. Always be polite, concise, and accurate.

--- Sample 1 ---
You are Aria, a helpful e-commerce assistant. You help customers search for products, track orders, manage returns, answer questions, and resolve issues. Always be polite, concise, and accurate.

--- Sample 2 ---
You are Aria, a helpful e-commerce assistant. You help customers search for products, track orders, manage returns, answer questions, and resolve issues. Always be polite, concise, and accurate.

--- Sample 3 ---
You are Aria, a helpful e-commerce assistant. You help customers search for products, track orders, manage returns, answer questions, and resolve issues. Always be polite, concise, and accurate.

--- Sample 4 ---
You are Aria, a helpful e-commerce assistant. You help customers search for products, track orders, manage returns, answer questions, and resolve issues. Always be polite, concise, and accurate.

================================================================================
HISTORY
================================================================================

--- Sample 0 ---
[]

--- Sample 1 ---
[]

--- Sample 2 ---
[]

--- Sample 3 ---
[]

--- Sample 4 ---
[]

================================================================================
CONTEXT
================================================================================

--- Sample 0 ---
{"retrieved_docs": [], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- Sample 1 ---
{"retrieved_docs": ["Quaker Oats 2kg by Quaker. Type: breakfast oats. Key feature: high fibre. Price: \u20b9399. Domain: grocery_food."], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- Sample 2 ---
{"retrieved_docs": [], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- Sample 3 ---
{"retrieved_docs": [], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- Sample 4 ---
{"retrieved_docs": ["Prestige Induction Cooktop by Prestige. Type: induction cooktop. Key feature: energy saving. Price: \u20b92499. Domain: home_kitchen."], "user_profile": {}, "cart_state": {}, "order_details": {}}

================================================================================
TOOLS
================================================================================

--- Sample 0 ---
[{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

--- Sample 1 ---
[]

--- Sample 2 ---
[{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

--- Sample 3 ---
[{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

--- Sample 4 ---
[]

================================================================================
RESPONSE
================================================================================

--- Sample 0 ---
{"name": "initiate_exchange", "arguments": {"order_id": "ORD-47172"}}

--- Sample 1 ---
Good morning!

The Quaker Oats 2kg product is **not certified gluten-free**. While oats are naturally gluten-free, they are often processed in facilities that also handle gluten-containing grains, leading to potential cross-contamination. If you require a strictly gluten-free option, I recommend looking for products specifically labeled "certified gluten-free oats."

Regarding added sugars and artificial sweeteners, the Quaker Oats 2kg product (which is typically traditional rolled oats) generally **does not contain added sugars or artificial sweeteners**. It is usually 100% whole grain rolled oats.

For a healthy and natural breakfast, these traditional rolled oats are an excellent choice! You can always add your own natural sweeteners like fruit, honey, or maple syrup if desired.

--- Sample 2 ---
{"name": "log_complaint", "arguments": {"order_id": "ORD-59948", "item": "Fluke 117 multimeter", "reason": "stopped working after a week"}}
I've logged your complaint about the Fluke 117 multimeter from order ORD-59948. We'll investigate this issue for you.

--- Sample 3 ---
{"name": "log_complaint", "arguments": {"order_id": "ORD-13033", "item": "Razer DeathAdder V3", "issue": "stopped working after only a month"}}
I've logged a complaint regarding your Razer DeathAdder V3. We'll investigate this issue for you.

--- Sample 4 ---
Certainly! Here's a comparison between the Prestige Induction Cooktop and the Instant Pot Duo 7-in-1:

**Prestige Induction Cooktop:**

*   **Primary Function:** Designed specifically for cooking with induction-compatible cookware. It provides precise temperature control and fast heating.
*   **Key Features:**
    *   Energy efficient (uses electromagnetic fields to heat the pan directly).
    *   Faster cooking times compared to traditional gas or electric stoves.
    *   Easy to clean flat surface.
    *   Often includes pre-set cooking menus and safety features like auto-off.
*   **Best For:** Those who want a dedicated cooktop for everyday cooking, especially if they value speed, energy efficiency, and precise temperature control. It's an excellent addition to a kitchen or for small spaces.
*   **Limitations:** Requires induction-compatible cookware. It's a single-purpose appliance for cooking on a stovetop.

**Instant Pot Duo 7-in-1:**

*   **Primary Function:** A multi-cooker that combines seven appliances in one: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer.
*   **Key Features:**
    *   Versatile for a wide range of cooking methods.
    *   Pressure cooking significantly reduces cooking time for many dishes.
    *   "Set it and forget it" functionality for slow cooking

In [ ]:
for i in range(5):
        print(f"\n--- Sample {i} ---")
        print(dataset["train"][i]["prompt"])

--- Sample 0 ---
Hey there, I just got my Dyson V12 vacuum cleaner (order #ORD-47172) and it's not really what I was expecting. Is there a way to exchange it for a different model?

--- Sample 1 ---
Good morning. I am considering purchasing the Quaker Oats 2kg product from your grocery section. Could you please clarify if this particular product is gluten-free and if it contains any added sugars or artificial sweeteners? I am looking for a healthy and natural breakfast option.

--- Sample 2 ---
Hey, my Fluke 117 multimeter from order ORD-59948 just stopped working after a week. What do I do now?

--- Sample 3 ---
Hey, my Razer DeathAdder V3 just stopped working after only a month! My order ID is ORD-13033, can you help me out?

--- Sample 4 ---
Hey, can you compare the Prestige Induction Cooktop with the Instant Pot Duo 7-in-1 for me?

In [2]:
import pandas as pd

train_df = dataset["train"].to_pandas()
test_df = dataset["test"].to_pandas()

def missing_report(df):
  report = pd.DataFrame({
      "null_count": df.isna().sum(),
      "null_pct": df.isna().mean()*100,
      "empty_string_count": df.eq("").sum(),
      "empty_string_pct": df.eq("").mean()*100
  })
  return report.sort_values("null_count", ascending=False)

train_missing = missing_report(train_df)

train_missing

                 null_count  null_pct  empty_string_count  empty_string_pct
test_tier             32061  91.04876                3152           8.95124
capability            32061  91.04876                   0           0.00000
group                     0   0.00000                   0           0.00000
source                    0   0.00000                   0           0.00000
id                        0   0.00000                   0           0.00000
system                    0   0.00000                   0           0.00000
difficulty                0   0.00000                   0           0.00000
history                   0   0.00000                   0           0.00000
prompt                    0   0.00000                   0           0.00000
response_type             0   0.00000                   0           0.00000
response                  0   0.00000                   0           0.00000
context                   0   0.00000                   0           0.00000
tools                     0   0.00000                   0           0.00000
locale                    0   0.00000                   0           0.00000
language                  0   0.00000                   0           0.00000
annotator                 0   0.00000                   0           0.00000
quality_score             0   0.00000                   0           0.00000
intent_category           0   0.00000                   0           0.00000
domain                    0   0.00000                   0           0.00000
sub_intent                0   0.00000                   0           0.00000
intent                    0   0.00000                   0           0.00000

In [ ]:
categorical_cols = [
    "source",
    "group",
    "response_type",
    "language",
    "locale",
    "domain",
    "intent_category",
    "intent",
    "sub_intent",
    "capability",
    "test_tier",
]

for col in categorical_cols:
    print(f"\n{'=' * 60}")
    print(f"{col.upper()}")
    print(f"Unique values: {train_df[col].nunique(dropna=False)}")
    print(train_df[col].value_counts(dropna=False).head(30))

============================================================
SOURCE
Unique values: 47
source
bitext_customer_support                            4000
bitext_retail_ecom                                 3999
synthetic_api_generated                            3152
asos_ecom_dataset                                  1589
amazon_reviews_2023_video_games                     852
amazon_reviews_2023_health_and_household            847
amazon_reviews_2023_pet_supplies                    844
amazon_reviews_2023_toys_and_games                  842
amazon_reviews_2023_clothing_shoes_and_jewelry      840
amazon_reviews_2023_electronics                     840
amazon_reviews_2023_beauty_and_personal_care        839
amazon_reviews_2023_books                           837
amazon_reviews_2023_cell_phones_and_accessories     835
amazon_reviews_2023_home_and_kitchen                834
amazon_reviews_2023_grocery_and_gourmet_food        833
amazon_reviews_2023_sports_and_outdoors             832
amazon_reviews_2023_appliances                      575
amazon_reviews_2023_musical_instruments             570
amazon_reviews_2023_arts_crafts_and_sewing          570
amazon_reviews_2023_patio_lawn_and_garden           564
amazon_reviews_2023_handmade_products               563
amazon_reviews_2023_tools_and_home_improvement      561
amazon_reviews_2023_baby_products                   561
amazon_reviews_2023_office_products                 560
amazon_reviews_2023_automotive                      536
amazon_meta_2023_electronics                        400
amazon_meta_2023_automotive                         400
amazon_meta_2023_baby_products                      400
amazon_meta_2023_office_products                    400
amazon_meta_2023_sports_and_outdoors                400
Name: count, dtype: int64

============================================================
GROUP
Unique values: 3
group
B    26478
A     7529
C     1206
Name: count, dtype: int64

============================================================
RESPONSE_TYPE
Unique values: 3
response_type
text         26478
tool_call     7529
mixed         1206
Name: count, dtype: int64

============================================================
LANGUAGE
Unique values: 2
language
en       35121
hi-en       92
Name: count, dtype: int64

============================================================
LOCALE
Unique values: 2
locale
en-US    35121
en-IN       92
Name: count, dtype: int64

============================================================
DOMAIN
Unique values: 22
domain
general            8836
electronics        3485
fashion            3356
home               3334
books_media        3016
sports_outdoors    1447
beauty             1372
pets               1244
grocery            1233
arts_crafts        1133
baby                961
office              960
automotive          936
health              847
toys_games          842
industrial          619
gaming              306
appliances          296
garden_outdoor      291
grocery_food        241
pet_supplies        241
home_kitchen        217
Name: count, dtype: int64

============================================================
INTENT_CATEGORY
Unique values: 7
intent_category
product_discovery    23324
order_management      6313
returns_exchanges     2666
customer_support      2405
general_info           291
cart_checkout          114
account                100
Name: count, dtype: int64

============================================================
INTENT
Unique values: 19
intent
product_detail_qa               12806
bundle_suggestions               4198
similarity_search                3695
reorder_assistance               3643
order_cancellation               1682
exchange_request                 1680
order_status                      988
return_refund                     986
product_search                    973
payment_issues                    927
account_management                878
stock_availability                863
faq_answering                     563
gift_recommendation               359
product_comparison                351
complaint_handling                348
cart_management                   114
human_handoff                      80
personalized_recommendations       79
Name: count, dtype: int64

============================================================
SUB_INTENT
Unique values: 88
sub_intent
product_description          6516
find_similar                 3462
reorder_same_item            3390
complementary_products       3165
specifications               2991
reviews_ratings              2334
cancel_before_shipment       1563
ingredients_materials         835
order_modification            807
refund_eligibility            795
address_management            771
add_to_cart                   766
cross_sell                    716
in_stock_check                683
track_order                   602
exchange_same_variant         456
payment_processing            354
payment_method_update         350
return_policy                 331
exchange_different_item       304
upsell                        264
reorder_with_modification     216
find_alternatives             208
shipping_update               183
occasion_gift                 132
brand_compare                 127
budget_gift                   122
price_compare                 119
complaint_filed               113
escalation_request            105
Name: count, dtype: int64

============================================================
CAPABILITY
Unique values: 20
capability
None                            32061
gift_recommendation               359
product_comparison                351
complaint_handling                320
faq_answering                     291
stock_availability                258
product_search                    207
return_refund                     188
order_status                      188
payment_issues                    137
product_detail_qa                 130
cart_management                   114
exchange_request                  113
account_management                100
order_cancellation                 87
human_handoff                      80
bundle_suggestions                 79
personalized_recommendations       79
reorder_assistance                 37
similarity_search                  34
Name: count, dtype: int64

============================================================
TEST_TIER
Unique values: 2
test_tier
None    32061
         3152
Name: count, dtype: int64

In [ ]:
train_ids = set(train_df["id"])
test_ids = set(test_df["id"])

train_prompts = set(train_df["prompt"])
test_prompts = set(test_df["prompt"])

print("ID overlap:", len(train_ids & test_ids))
print("Exact prompt overlap:", len(train_prompts & test_prompts))

ID overlap: 0
Exact prompt overlap: 327

In [ ]:
overlap_prompts = train_prompts & test_prompts

train_overlap = train_df[
    train_df["prompt"].isin(overlap_prompts)
].copy()

test_overlap = test_df[
    test_df["prompt"].isin(overlap_prompts)
].copy()

print("Unique overlapping prompts:", len(overlap_prompts))
print("Train rows involved:", len(train_overlap))
print("Test rows involved:", len(test_overlap))

Unique overlapping prompts: 327
Train rows involved: 2667
Test rows involved: 904

In [ ]:
# آیا prompt مشترک، metadata متفاوت دارد؟
comparison_cols = [
    "source",
    "intent_category",
    "intent",
    "sub_intent",
    "domain",
    "response_type",
    "tools",
    "context",
]

for col in comparison_cols:
    train_values = (
        train_overlap.groupby("prompt")[col]
        .apply(lambda x: set(x))
    )

    test_values = (
        test_overlap.groupby("prompt")[col]
        .apply(lambda x: set(x))
    )

    comparable = pd.DataFrame({
        "train": train_values,
        "test": test_values
    })

    comparable["same"] = comparable["train"] == comparable["test"]

    print(f"\n{col}")
    print("Same:", comparable["same"].sum())
    print("Different:", (~comparable["same"]).sum())

source
Same: 0
Different: 327

intent_category
Same: 189
Different: 138

intent
Same: 64
Different: 263

sub_intent
Same: 35
Different: 292

domain
Same: 17
Different: 310

response_type
Same: 326
Different: 1

tools
Same: 326
Different: 1

context
Same: 2
Different: 325

In [ ]:
sample_overlap = (
    train_overlap[
        [
            "id",
            "source",
            "prompt",
            "intent_category",
            "intent",
            "sub_intent",
            "response_type",
            "tools",
            "context",
            "response",
        ]
    ]
    .sort_values("prompt")
)

sample_overlap.head(20).to_string(index=False)

'            id                                          source                                 prompt   intent_category             intent             sub_intent response_type tools                                                                                                                                                                                                                                                                                                                                                                     context                                                                                                                                                                                                                                                                                 response\necomm_bb8c94ab                  amazon_reviews_2023_appliances Tell me about this product: A Good Buy product_discovery  product_detail_qa  ingredients_materials          text    []                                                                                                                                                                                          {"retrieved_docs": ["It\'s well-made of quality materials, works as it should, and holds up very well. No complaints."], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                          It\'s well-made of quality materials, works as it should, and holds up very well. No complaints.\necomm_768f59b4             amazon_reviews_2023_office_products    Tell me about this product: AWESOME product_discovery bundle_suggestions complementary_products          text    []                                                                                                                             {"retrieved_docs": ["This is for use with the label maker which is an amazing little gadget<br /><br />UPDATE:  i ordered 2 more and got them today  i LOVEE this label maker  !!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                             This is for use with the label maker which is an amazing little gadget<br /><br />UPDATE:  i ordered 2 more and got them today  i LOVEE this label maker  !!\necomm_fdd6260b    amazon_reviews_2023_grocery_and_gourmet_food    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                               {"retrieved_docs": ["amazing  i knew they would be  placing 2nd order  they have the cheese ones too which are absolutely delicious too  i have to check out other flavors  these are ADDICTING better than any US cheese snack"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                               amazing  i knew they would be  placing 2nd order  they have the cheese ones too which are absolutely delicious too  i have to check out other flavors  these are ADDICTING better than any US cheese snack\necomm_377d6e65    amazon_reviews_2023_grocery_and_gourmet_food    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                   {"retrieved_docs": ["O-M-G  ........tiny jar but OMG !!!!!!!!!!!  well worth the price  its gonna be hard not to demolish the entire jar in 2 sittings LOL  gonna try some other brands too"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                   O-M-G  ........tiny jar but OMG !!!!!!!!!!!  well worth the price  its gonna be hard not to demolish the entire jar in 2 sittings LOL  gonna try some other brands too\necomm_cc14bc91                amazon_reviews_2023_kindle_store    Tell me about this product: AWESOME product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                       {"retrieved_docs": ["love all her books !!! she\'s awesome  if you love amish mysteries  read her Kate Burkholder series"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                       love all her books !!! she\'s awesome  if you love amish mysteries  read her Kate Burkholder series\necomm_f527fedc             amazon_reviews_2023_office_products    Tell me about this product: AWESOME product_discovery bundle_suggestions complementary_products          text    []                                                                                                                                                                                                                  {"retrieved_docs": ["These are much bigger than i was expecting large area to write in  !!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                  These are much bigger than i was expecting large area to write in  !!!!\necomm_f461805a amazon_reviews_2023_cell_phones_and_accessories    Tell me about this product: AWESOME product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                                                                                {"retrieved_docs": ["Sturdy, fantastic, well made.... AWESOME!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                                                Sturdy, fantastic, well made.... AWESOME!\necomm_82f22b35    amazon_reviews_2023_grocery_and_gourmet_food    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                                                                                                                                        {"retrieved_docs": ["DELICIOUS !!  fast shipper too ...  !!  thank you"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                                        DELICIOUS !!  fast shipper too ...  !!  thank you\necomm_cabbf1e5                 amazon_reviews_2023_electronics    Tell me about this product: AWESOME product_discovery  product_detail_qa         specifications          text    []                                                                                                                                                                                                                                     {"retrieved_docs": ["love it  and easy to put together !  perfect fit too"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                                     love it  and easy to put together !  perfect fit too\necomm_be26f670        amazon_reviews_2023_health_and_household    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                                                    {"retrieved_docs": ["i love these to clean the toilet  .. ive used them for years and its hard to find them in stores .. so glad Amazon has EVERYThing  !!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                    i love these to clean the toilet  .. ive used them for years and its hard to find them in stores .. so glad Amazon has EVERYThing  !!\necomm_66d2ddee    amazon_reviews_2023_grocery_and_gourmet_food    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                                                                                                                      {"retrieved_docs": ["love them  placing a 2nd order  ...  just like cheese puffs  yummmm"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                      love them  placing a 2nd order  ...  just like cheese puffs  yummmm\necomm_024b9f3b        amazon_reviews_2023_health_and_household    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                                                                                {"retrieved_docs": ["love this product very FILLING and it makes great smoothies when you add fruit, nuts, veggies, etc.  !!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                love this product very FILLING and it makes great smoothies when you add fruit, nuts, veggies, etc.  !!!!\necomm_30da410b                amazon_reviews_2023_pet_supplies    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                            {"retrieved_docs": ["awesome just what i needed for my newly acquired rescue who is a maine coon and was full of knots<br />those knots hurt them and can cause infections  i ordered so many things from here  but this is what i really needed just get rid of those nasty knots"], "user_profile": {}, "cart_state": {}, "order_details": {}}                            awesome just what i needed for my newly acquired rescue who is a maine coon and was full of knots<br />those knots hurt them and can cause infections  i ordered so many things from here  but this is what i really needed just get rid of those nasty knots\necomm_54048a16                 amazon_reviews_2023_electronics    Tell me about this product: AWESOME product_discovery  product_detail_qa    product_description          text    [] {"retrieved_docs": ["a friend told me he had this and it was great  .. ive been looking at it and looking at it .. and he convinced me i needed it  ... alexa is pretty funny at times ...  i saw that angel stand for it  .. i wish they had more choices  ... nothing caught my eye  maybe someday one will"], "user_profile": {}, "cart_state": {}, "order_details": {}} a friend told me he had this and it was great  .. ive been looking at it and looking at it .. and he convinced me i needed it  ... alexa is pretty funny at times ...  i saw that angel stand for it  .. i wish they had more choices  ... nothing caught my eye  maybe someday one will\necomm_84b78bf5      amazon_reviews_2023_arts_crafts_and_sewing    Tell me about this product: AWESOME product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                                                                                  {"retrieved_docs": ["Love this !!!  Great value too !!!!!!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                                                  Love this !!!  Great value too !!!!!!!!\necomm_175e59cc    amazon_reviews_2023_grocery_and_gourmet_food    Tell me about this product: AWESOME  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                                                                                                                                        {"retrieved_docs": ["DELICIOUS !!  fast shipper too ...  !!  thank you"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                                                                        DELICIOUS !!  fast shipper too ...  !!  thank you\necomm_357acaa4              amazon_reviews_2023_toys_and_games    Tell me about this product: AWESOME product_discovery  product_detail_qa        reviews_ratings          text    []                                                 {"retrieved_docs": ["love this  very helpful  i just did a  24X30 1000 piece though  certainly not enough space until i did a good portion of it  .. but i wish i had this years back when i was sorting pieces  highly recommended for any jigsaw enthusiast"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                 love this  very helpful  i just did a  24X30 1000 piece though  certainly not enough space until i did a good portion of it  .. but i wish i had this years back when i was sorting pieces  highly recommended for any jigsaw enthusiast\necomm_c538bd5e                    amazon_reviews_2023_software  Tell me about this product: Addictive product_discovery  product_detail_qa        reviews_ratings          text    []                                                                                                                                                                                    {"retrieved_docs": ["Fast paced game. Once you start you will keep playing. If you like puzzle games this game is for you!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                                                    Fast paced game. Once you start you will keep playing. If you like puzzle games this game is for you!\necomm_609a2f8d    amazon_reviews_2023_grocery_and_gourmet_food  Tell me about this product: Addictive  order_management reorder_assistance      reorder_same_item          text    []                                                                                                                                                 {"retrieved_docs": ["These are so good!!! In fact I like them so much that I\'ve ordered twice for me and have sent my friends bags of these for Christmas!!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                                                                                                                 These are so good!!! In fact I like them so much that I\'ve ordered twice for me and have sent my friends bags of these for Christmas!!!!\necomm_c47eb670    amazon_reviews_2023_grocery_and_gourmet_food Tell me about this product: Addictive!  order_management reorder_assistance      reorder_same_item          text    []                                                        {"retrieved_docs": ["These double dipped peanuts live up to their name.  They are coated generously in a delicious milk chocolate and I find it so hard to stop eating them.  They are so yummy and worth every penny.  You won\'t regret buying these."], "user_profile": {}, "cart_state": {}, "order_details": {}}                                                        These double dipped peanuts live up to their name.  They are coated generously in a delicious milk chocolate and I find it so hard to stop eating them.  They are so yummy and worth every penny.  You won\'t regret buying these.'

In [ ]:
import pandas as pd

rng = 42

sample_prompts = (
    pd.Series(list(overlap_prompts))
    .sample(10, random_state=rng)
    .tolist()
)

for i, prompt in enumerate(sample_prompts, 1):
    print("=" * 100)
    print(f"SAMPLE {i}")
    print("\nPROMPT:")
    print(prompt)

    print("\n--- TRAIN ---")
    print(
        train_overlap[
            train_overlap["prompt"] == prompt
        ][
            [
                "source",
                "intent_category",
                "intent",
                "sub_intent",
                "response_type",
                "tools",
                "context",
            ]
        ].to_string(index=False)
    )

    print("\n--- TEST ---")
    print(
        test_overlap[
            test_overlap["prompt"] == prompt
        ][
            [
                "source",
                "intent_category",
                "intent",
                "sub_intent",
                "response_type",
                "tools",
                "context",
            ]
        ].to_string(index=False)
    )

====================================================================================================
SAMPLE 1

PROMPT:
Tell me about this product: convenient

--- TRAIN ---
                                      source   intent_category             intent          sub_intent response_type tools                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                context
              amazon_reviews_2023_gift_cards product_discovery  product_detail_qa product_description          text    []                                                                                                                                                                                                                                                                                                                                                                                {"retrieved_docs": ["A great and convenient gift idea-price is right too!"], "user_profile": {}, "cart_state": {}, "order_details": {}}
             amazon_reviews_2023_electronics product_discovery  product_detail_qa product_description          text    []                                                                                                                                                                                                                          {"retrieved_docs": ["I have a whole DVD library that I will NOT be trading in for &#34;blue ray&#34;... and it is SO convenient to load up to 6 movies and watch a series or sequel set.  Nice.  Love it.  So far, works great."], "user_profile": {}, "cart_state": {}, "order_details": {}}
amazon_reviews_2023_grocery_and_gourmet_food  order_management reorder_assistance   reorder_same_item          text    [] {"retrieved_docs": ["In my opinion, the best part of this boil is that it comes in a bag.  Clean up is much easier.  I like the flavor, not to overwhelming and yet effective.  It smells accurate to the taste. I haven't seen this boil in a bag at the store, so I cannot compare the price.  It might be easier to buy a smaller amount to &#34;try&#34; it for taste.  A pack of 12 is a commitment unless you're like me and have a HUGE boil pot."], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- TEST ---
                                         source   intent_category            intent     sub_intent response_type tools                                                                                                                                                                                                                      context
amazon_reviews_2023_cell_phones_and_accessories product_discovery product_detail_qa specifications          text    [] {"retrieved_docs": ["didn't work after I added a case to my phone, even with rubber bumper removed but my daughter benefited from my purchase and she loves it"], "user_profile": {}, "cart_state": {}, "order_details": {}}
====================================================================================================
SAMPLE 2

PROMPT:
Tell me about this product: Gift

--- TRAIN ---
                                        source   intent_category             intent             sub_intent response_type tools                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   context
                amazon_reviews_2023_gift_cards product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                                                                                                                                                                                                                                                  {"retrieved_docs": ["Easily used anywhere."], "user_profile": {}, "cart_state": {}, "order_details": {}}
amazon_reviews_2023_clothing_shoes_and_jewelry product_discovery  similarity_search           find_similar          text    []                                                                                                                                                                                                                                                                                                                       {"retrieved_docs": ["Bought for my grand daughter, my daughter said they were nice, she said they are holing up good and washing good"], "user_profile": {}, "cart_state": {}, "order_details": {}}
          amazon_reviews_2023_home_and_kitchen product_discovery bundle_suggestions complementary_products          text    [] {"retrieved_docs": ["Son-in-law wanted something to fit all his movies.<br />Since I use the smaller size I thought I get this for him.<br />He likes the case but really would have like to have 3 ring binder capability vs this plastic tabs.<br />they hold but moving movies around in the case are a big pain the butt - he used a few different words to communicate that to us.<br />unfortunately we can't find the 3 ring binder version anymore."], "user_profile": {}, "cart_state": {}, "order_details": {}}
                amazon_reviews_2023_gift_cards product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                                                                                                                                                                                                                                                  {"retrieved_docs": ["Easily used anywhere."], "user_profile": {}, "cart_state": {}, "order_details": {}}
            amazon_reviews_2023_toys_and_games product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                          {"retrieved_docs": ["Got this for my granddaughters ages 2 and 4. The 2 year old did one and said she was done (which I kind of figured she would)  so, the 4 year old was happy to do the other 5. Their Mom said they enjoyed the kit and they turned out great."], "user_profile": {}, "cart_state": {}, "order_details": {}}
                     amazon_reviews_2023_books product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                                                                                                                                                                                                                                               {"retrieved_docs": ["Was a gift, she loved it"], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- TEST ---
                                 source   intent_category            intent          sub_intent response_type tools                                                                                                     context
        amazon_reviews_2023_video_games product_discovery product_detail_qa product_description          text    [] {"retrieved_docs": ["Was a gift they loved it"], "user_profile": {}, "cart_state": {}, "order_details": {}}
amazon_reviews_2023_sports_and_outdoors product_discovery similarity_search        find_similar          text    []     {"retrieved_docs": ["Just what was wanted"], "user_profile": {}, "cart_state": {}, "order_details": {}}
====================================================================================================
SAMPLE 3

PROMPT:
Tell me about this product: Wow

--- TRAIN ---
                                        source   intent_category             intent          sub_intent response_type tools                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       context
    amazon_reviews_2023_arts_crafts_and_sewing product_discovery  product_detail_qa product_description          text    []                                                                                                                                                                                                                                                                                   {"retrieved_docs": ["I have been making wreaths for several months and struggling to make bows. I finally bought this Bowdabra and today made my first really nice bow on my 1st attempt. Easy to use, great value...love it!"], "user_profile": {}, "cart_state": {}, "order_details": {}}
      amazon_reviews_2023_health_and_household  order_management reorder_assistance   reorder_same_item          text    []                                                                                                                                                                                                                                                                                                                                                                                       {"retrieved_docs": ["These christmas bags were super thick.  Very worth the money especially since I received a discount."], "user_profile": {}, "cart_state": {}, "order_details": {}}
               amazon_reviews_2023_electronics product_discovery  product_detail_qa product_description          text    []                                                                                                                                                                                                                                                                                                                                                                                                           {"retrieved_docs": ["This is awesome!!! Staying in RV for 2 months and we are so happy we got this!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}
  amazon_reviews_2023_grocery_and_gourmet_food  order_management reorder_assistance   reorder_same_item          text    []                                                                                                                                                                                                                                                                                                      {"retrieved_docs": ["Wow! Some of the reviews indicated that these lacked butteryness or salt. I thought they were Perfect! Smooth! Creamy! Very soft! A Burst of Flavor in the mouth! Highly recommend!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}
amazon_reviews_2023_clothing_shoes_and_jewelry product_discovery  similarity_search        find_similar          text    []                                                                                                                                                                                                                                                {"retrieved_docs": ["This was my first pair of Sketchers and I honestly only got them because they were on sale for $20!!But they are Sooooooooo Comfortable!  I\u2019m normally a 9. They fit true to size. No complaints! And this won\u2019t be my last pair!"], "user_profile": {}, "cart_state": {}, "order_details": {}}
                amazon_reviews_2023_appliances product_discovery  product_detail_qa product_description          text    []                                                                                                                                                                                                                    {"retrieved_docs": ["I live out here in Arizona, I put this little refrigerator in my bathroom because I have a lot of products that I put on my face and serum\u2019s , creams body lotion and other things. It came dented but I would not send it back because it works just as expected!"], "user_profile": {}, "cart_state": {}, "order_details": {}}
            amazon_reviews_2023_toys_and_games product_discovery  product_detail_qa product_description          text    [] {"retrieved_docs": ["This is my 1st puzzle buy this maker. I am very impressed with everything you get with it in the box. You get a good quality puzzle, Sticky sheets to put the puzzle on so you don't have to glue it if you wanna keep it... And little cardboard dividers that you put in the box to use to sort your pc in.No other puzzle maker Gives you all this As well as a great Puzzle. For me it was a Challenge because I don't usually do thousand pc puzzles....But I really like the picture"], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- TEST ---
                                        source   intent_category             intent             sub_intent response_type tools                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   context
amazon_reviews_2023_tools_and_home_improvement product_discovery bundle_suggestions complementary_products          text    []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {"retrieved_docs": ["Half the price of hardware store!!! It's great"], "user_profile": {}, "cart_state": {}, "order_details": {}}
  amazon_reviews_2023_beauty_and_personal_care product_discovery  product_detail_qa         specifications          text    []                                                                                                                                                                           {"retrieved_docs": ["I havent had a relaxer in over 2 years. I was Very hesitant about this product but brought it on a whim for $8 at Dollar General. As soon as I put the product on my hair it immediately removed 80% of my frizz. I almost cried because the day before I was Seriously considering cutting my hair all off. I was unable to get to the salon and even at 33, am still figuring out which products work for my hair. But this was a Pleasant surprise. It was the Perfect weight for my hair and smelled Wonderful!! After applying the product I was able to do one pass through my hair with the flat iron and my hair went from dry and unmanageable (a little rain Also got on it during the day) to shiny and soft. I was Amazed and will try out the other products in the line. I only took away one star away because I just wrapped my hair and am unsure how it will look in the morning. I will update later. :-)"], "user_profile": {}, "cart_state": {}, "order_details": {}}
  amazon_reviews_2023_beauty_and_personal_care product_discovery  product_detail_qa    product_description          text    []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {"retrieved_docs": ["I\u2019ve never used cuticle oil before so I don\u2019t have anything to compare it to, but I can Definitely tell the difference in using and not using it. Hours later and several hand washes after applying and my cuticles still look nourished and moisturized on my chocolate skin. Iam Very Impressed!!! It was very easy to apply and the bottle should last a Good While. At least a year!! Yes!! Buy it!!!"], "user_profile": {}, "cart_state": {}, "order_details": {}}

In [ ]:
train_pair = set(
    zip(
        train_df["prompt"],
        train_df["context"]
    )
)

test_pair = set(
    zip(
        test_df["prompt"],
        test_df["context"]
    )
)

pair_overlap = train_pair & test_pair

print("Train prompt+context pairs:", len(train_pair))
print("Test prompt+context pairs:", len(test_pair))
print("Exact prompt+context overlap:", len(pair_overlap))

Train prompt+context pairs: 34671
Test prompt+context pairs: 8671
Exact prompt+context overlap: 2

In [ ]:
overlap_pairs = train_pair & test_pair

for i, (prompt, context) in enumerate(overlap_pairs, 1):
    print("=" * 100)
    print(f"OVERLAP {i}")

    print("\nPROMPT:")
    print(prompt)

    print("\nCONTEXT:")
    print(context)

    print("\n--- TRAIN ---")
    print(
        train_df[
            (train_df["prompt"] == prompt) &
            (train_df["context"] == context)
        ][
            [
                "id",
                "source",
                "intent_category",
                "intent",
                "sub_intent",
                "response_type",
                "tools",
                "response",
            ]
        ].to_string(index=False)
    )

    print("\n--- TEST ---")
    print(
        test_df[
            (test_df["prompt"] == prompt) &
            (test_df["context"] == context)
        ][
            [
                "id",
                "source",
                "intent_category",
                "intent",
                "sub_intent",
                "response_type",
                "tools",
                "response",
            ]
        ].to_string(index=False)
    )

====================================================================================================
OVERLAP 1

PROMPT:
Tell me about this product: Screen protectors

CONTEXT:
{"retrieved_docs": ["As long as you follow the directions EXACTLY, it\u2019s easy to apply"], "user_profile": {}, "cart_state": {}, "order_details": {}}

--- TRAIN ---
            id                                          source   intent_category            intent          sub_intent response_type tools                                                         response
ecomm_68f657c0 amazon_reviews_2023_cell_phones_and_accessories product_discovery product_detail_qa product_description          text    [] As long as you follow the directions EXACTLY, it’s easy to apply

--- TEST ---
            id                          source   intent_category            intent          sub_intent response_type tools                                                         response
ecomm_19ee5174 amazon_reviews_2023_electronics product_discovery product_detail_qa product_description          text    [] As long as you follow the directions EXACTLY, it’s easy to apply
====================================================================================================
OVERLAP 2

PROMPT:
can I check your refund policy?

CONTEXT:
{"user_profile": {}, "retrieved_docs": [], "cart_state": {}, "order_details": {}}

--- TRAIN ---
            id                  source   intent_category        intent         sub_intent response_type                                                                                                                                                                                                                                                                                                               tools                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  response
ecomm_b571df38 bitext_customer_support returns_exchanges return_refund refund_eligibility     tool_call [{"type": "function", "function": {"name": "initiate_return", "description": "Initiate a return and generate a return label", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}, "item_sku": {"type": "string"}}, "required": ["order_id", "reason"]}}}] Indeed! I genuinely appreciate your interest in reviewing our refund policy. Understanding the terms and conditions that govern refunds is essential for a seamless customer experience. Allow me to provide you with the information you seek.\n\nOur refund policy is designed to protect your rights as a valued customer. Here's a summary of our general guidelines:\n\n1. **Product/Service Defect:** If you discover that the product or service you purchased has a defect or does not meet the description provided, you are usually eligible for a refund.\n\n2. **Cancellation within Grace Period:** If you change your mind and decide to cancel your purchase within the specified grace period, you should be able to receive a refund.\n\n3. **Unauthorized Charges:** We understand that unauthorized charges can be concerning. If you spot any unfamiliar transactions on your account, please notify us immediately, and we will investigate and assist you accordingly.\n\n4. **Event Cancellation:** If you have purchased tickets for an event that gets canceled and no alternate date is scheduled, you typically have the option for a refund.\n\n5. **Duplicate Charges:** In case you notice duplicate charges for the same item on your payment statement, please reach out to us, and we will rectify the situation promptly.\n\n6. **Non-receipt of Goods:** If you have not received your ordered product within the estimated delivery time, please let us know, as you may qualify for a refund.\n\nHowever, please keep in mind that refund policies may vary depending on the specific vendor or service provider. It is always advisable to consult the vendor directly or review the terms and conditions for detailed information.\n\nIf you require further assistance or have any specific questions regarding a particular order or circumstance, please provide me with the relevant details or order number, and I will be more than happy to assist you further. Your satisfaction is our top priority!\n\nIs there anything else I can help you with today?

--- TEST ---
            id             source  intent_category        intent    sub_intent response_type tools                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     response
ecomm_9243b5d0 bitext_retail_ecom customer_support faq_answering return_policy          text    [] I'm happy to help! I'd be happy to provide you with the details of our refund policy. Our priority is to ensure your satisfaction with our products and services. Here are the key points of our refund policy:\n\n1. Timeframe: We offer a 5-day refund window from the date of purchase.\n2. Eligibility: Refunds are available for Wireless Bluetooth Headphones and similar items that meet certain criteria.\n3. Condition: The product should be returned unused, with all original packaging and tags intact.\n4. Refund Process: To initiate a refund, please reach out to our our customer support team with your ORD-86139647 and a brief explanation.\n5. Refund Method: Refunds are issued through the same payment method used for the original purchase.\n\nPlease keep in mind that some exceptions may apply based on specific product categories or promotional offers. For more detailed information, you can visit our website's refund policy page or reach out to our our customer support team. We appreciate your understanding, and we're here to assist you with any further inquiries regarding our refund policy.

In [ ]:
print("TRAIN")
print("Rows:", len(train_df))
print("Unique prompt:", train_df["prompt"].nunique())
print("Unique prompt+context:", train_df[["prompt", "context"]].drop_duplicates().shape[0])

print("\nTEST")
print("Rows:", len(test_df))
print("Unique prompt:", test_df["prompt"].nunique())
print("Unique prompt+context:", test_df[["prompt", "context"]].drop_duplicates().shape[0])

TRAIN
Rows: 35213
Unique prompt: 31283
Unique prompt+context: 34671

TEST
Rows: 8818
Unique prompt: 8007
Unique prompt+context: 8671

In [ ]:
train_sources = set(train_df["source"])
test_sources = set(test_df["source"])

source_overlap = train_sources & test_sources

print("Train sources:", len(train_sources))
print("Test sources:", len(test_sources))
print("Sources appearing in both:", len(source_overlap))
print("Overlap sources:")
print(sorted(source_overlap))

Train sources: 47
Test sources: 47
Sources appearing in both: 47
Overlap sources:
['amazon_meta_2023_automotive', 'amazon_meta_2023_baby_products', 'amazon_meta_2023_clothing_shoes_and_jewelry', 'amazon_meta_2023_electronics', 'amazon_meta_2023_grocery_and_gourmet_food', 'amazon_meta_2023_home_and_kitchen', 'amazon_meta_2023_office_products', 'amazon_meta_2023_pet_supplies', 'amazon_meta_2023_sports_and_outdoors', 'amazon_meta_2023_tools_and_home_improvement', 'amazon_reviews_2023_all_beauty', 'amazon_reviews_2023_amazon_fashion', 'amazon_reviews_2023_appliances', 'amazon_reviews_2023_arts_crafts_and_sewing', 'amazon_reviews_2023_automotive', 'amazon_reviews_2023_baby_products', 'amazon_reviews_2023_beauty_and_personal_care', 'amazon_reviews_2023_books', 'amazon_reviews_2023_cds_and_vinyl', 'amazon_reviews_2023_cell_phones_and_accessories', 'amazon_reviews_2023_clothing_shoes_and_jewelry', 'amazon_reviews_2023_digital_music', 'amazon_reviews_2023_electronics', 'amazon_reviews_2023_gift_cards', 'amazon_reviews_2023_grocery_and_gourmet_food', 'amazon_reviews_2023_handmade_products', 'amazon_reviews_2023_health_and_household', 'amazon_reviews_2023_home_and_kitchen', 'amazon_reviews_2023_industrial_and_scientific', 'amazon_reviews_2023_kindle_store', 'amazon_reviews_2023_magazine_subscriptions', 'amazon_reviews_2023_movies_and_tv', 'amazon_reviews_2023_musical_instruments', 'amazon_reviews_2023_office_products', 'amazon_reviews_2023_patio_lawn_and_garden', 'amazon_reviews_2023_pet_supplies', 'amazon_reviews_2023_software', 'amazon_reviews_2023_sports_and_outdoors', 'amazon_reviews_2023_subscription_boxes', 'amazon_reviews_2023_tools_and_home_improvement', 'amazon_reviews_2023_toys_and_games', 'amazon_reviews_2023_unknown', 'amazon_reviews_2023_video_games', 'asos_ecom_dataset', 'bitext_customer_support', 'bitext_retail_ecom', 'synthetic_api_generated']

Tool calling Audit

In [3]:
import json
import pandas as pd


def parse_json(value):
    if value is None or value == "":
        return None

    try:
        return json.loads(value)
    except (json.JSONDecodeError, TypeError):
        return None


train_df["tools_parsed"] = train_df["tools"].apply(parse_json)
test_df["tools_parsed"] = test_df["tools"].apply(parse_json)

In [ ]:
print("Train rows:", len(train_df))
print("Test rows:", len(test_df))

print(
    "Train parsing failures:",
    train_df["tools_parsed"].isna().sum()
)

print(
    "Test parsing failures:",
    test_df["tools_parsed"].isna().sum()
)

Train rows: 35213
Test rows: 8818
Train parsing failures: 0
Test parsing failures: 0

In [ ]:
print(
    train_df["tools_parsed"]
    .apply(lambda x: isinstance(x, list))
    .value_counts()
)

tools_parsed
True    35213
Name: count, dtype: int64

In [4]:
def has_tools(x):
    return isinstance(x, list) and len(x) > 0


train_df["has_tools"] = train_df["tools_parsed"].apply(has_tools)
test_df["has_tools"] = test_df["tools_parsed"].apply(has_tools)

print("TRAIN")
print(train_df["has_tools"].value_counts())
print(train_df["has_tools"].value_counts(normalize=True) * 100)

print("\nTEST")
print(test_df["has_tools"].value_counts())
print(test_df["has_tools"].value_counts(normalize=True) * 100)

TRAIN
has_tools
False    26478
True      8735
Name: count, dtype: int64
has_tools
False    75.19382
True     24.80618
Name: proportion, dtype: float64

TEST
has_tools
False    6639
True     2179
Name: count, dtype: int64
has_tools
False    75.289181
True     24.710819
Name: proportion, dtype: float64

In [5]:
from collections import Counter


def extract_tool_names(tools):
    if not isinstance(tools, list):
        return []

    names = []

    for tool in tools:
        if not isinstance(tool, dict):
            continue

        function = tool.get("function", {})
        name = function.get("name")

        if name:
            names.append(name)

    return names


train_df["tool_names"] = train_df["tools_parsed"].apply(extract_tool_names)
test_df["tool_names"] = test_df["tools_parsed"].apply(extract_tool_names)


train_tool_counter = Counter(
    name
    for names in train_df["tool_names"]
    for name in names
)

test_tool_counter = Counter(
    name
    for names in test_df["tool_names"]
    for name in names
)

print("Unique tools - train:", len(train_tool_counter))
print("Unique tools - test:", len(test_tool_counter))

print("\nTRAIN")
print(train_tool_counter.most_common())

print("\nTEST")
print(test_tool_counter.most_common())

Unique tools - train: 12
Unique tools - test: 12

TRAIN
[('cancel_order', 1682), ('initiate_exchange', 1680), ('get_order_status', 988), ('initiate_return', 986), ('search_products', 973), ('log_payment_dispute', 927), ('update_account', 878), ('log_complaint', 348), ('add_to_cart', 114), ('update_cart_qty', 114), ('escalate_to_agent', 80), ('get_recommendations', 79)]

TEST
[('cancel_order', 421), ('initiate_exchange', 419), ('get_order_status', 248), ('initiate_return', 245), ('search_products', 241), ('log_payment_dispute', 232), ('update_account', 218), ('log_complaint', 88), ('add_to_cart', 29), ('update_cart_qty', 29), ('get_recommendations', 20), ('escalate_to_agent', 18)]

In [6]:
tool_schemas = {}

for _, row in train_df[train_df["has_tools"]].iterrows():
    for tool in row["tools_parsed"]:
        function = tool.get("function", {})
        name = function.get("name")

        if name and name not in tool_schemas:
            tool_schemas[name] = function


for name, schema in tool_schemas.items():
    parameters = schema.get("parameters", {})

    print("=" * 80)
    print(name)
    print("Description:", schema.get("description"))
    print("Properties:", list(parameters.get("properties", {}).keys()))
    print("Required:", parameters.get("required", []))

================================================================================
initiate_exchange
Description: Exchange an item for a different size or variant
Properties: ['order_id', 'item_sku', 'new_variant']
Required: ['order_id', 'item_sku', 'new_variant']
================================================================================
log_complaint
Description: Log a customer complaint and optionally escalate
Properties: ['order_id', 'issue', 'severity']
Required: ['issue', 'severity']
================================================================================
escalate_to_agent
Description: Transfer conversation to a live human agent
Properties: ['reason', 'priority', 'context_summary']
Required: ['reason', 'priority']
================================================================================
cancel_order
Description: Cancel an order if within the cancellation window
Properties: ['order_id', 'reason']
Required: ['order_id']
================================================================================
search_products
Description: Search the product catalog with filters
Properties: ['query', 'category', 'max_price', 'filters']
Required: ['query']
================================================================================
initiate_return
Description: Initiate a return and generate a return label
Properties: ['order_id', 'reason', 'item_sku']
Required: ['order_id', 'reason']
================================================================================
get_order_status
Description: Fetch live order status and tracking info
Properties: ['order_id', 'user_id']
Required: ['order_id']
================================================================================
get_recommendations
Description: Get personalised product recommendations
Properties: ['user_id', 'category', 'limit']
Required: ['user_id']
================================================================================
add_to_cart
Description: Add an item to the cart
Properties: ['sku', 'qty']
Required: ['sku']
================================================================================
update_cart_qty
Description: Update item quantity in cart
Properties: ['sku', 'qty']
Required: ['sku', 'qty']
================================================================================
log_payment_dispute
Description: Log a payment dispute and escalate to billing team
Properties: ['order_id', 'issue_type', 'amount']
Required: ['order_id', 'issue_type']
================================================================================
update_account
Description: Update user account details
Properties: ['user_id', 'field', 'value']
Required: ['user_id', 'field', 'value']

In [ ]:
train_df.columns

Index(['id', 'source', 'group', 'difficulty', 'system', 'history', 'prompt',
       'context', 'tools', 'response_type', 'response', 'language', 'locale',
       'annotator', 'quality_score', 'domain', 'intent_category', 'intent',
       'sub_intent', 'capability', 'test_tier', 'tools_parsed', 'has_tools',
       'tool_names'],
      dtype='object')

In [7]:
tool_response_df = train_df[
    train_df["response_type"].isin(["tool_call", "mixed"])
].copy()

print("Tool-related responses:", len(tool_response_df))

print(
    tool_response_df["response"]
    .head(10)
    .tolist()
)

Tool-related responses: 8735
['{"name": "initiate_exchange", "arguments": {"order_id": "ORD-47172"}}', '{"name": "log_complaint", "arguments": {"order_id": "ORD-59948", "item": "Fluke 117 multimeter", "reason": "stopped working after a week"}}\nI\'ve logged your complaint about the Fluke 117 multimeter from order ORD-59948. We\'ll investigate this issue for you.', '{"name": "log_complaint", "arguments": {"order_id": "ORD-13033", "item": "Razer DeathAdder V3", "issue": "stopped working after only a month"}}\nI\'ve logged a complaint regarding your Razer DeathAdder V3. We\'ll investigate this issue for you.', '{"name": "log_complaint", "arguments": {"order_id": "ORD-76093", "customer_id": "None", "reason": "damaged item", "action_requested": "replacement or refund"}}\nI\'ve logged your complaint about the damaged dumbbell set and requested a replacement or refund. We will investigate this issue and get back to you shortly.', '{"name": "log_complaint", "arguments": {"order_id": "ORD-35252", "complaint": "Book arrived damaged. Customer demands a full refund."}}\nI\'ve logged your complaint regarding the damaged book and your demand for a full refund.', '{"name": "escalate_to_agent", "arguments": {"customer_request": "The customer has specific questions about the fit and ideal activities for the Nike Air Max 270 and would like to chat with a human."}}\nI\'ve escalated your request to a human agent who will be able to help you with your specific questions.', '{"name": "cancel_order", "arguments": {"order_id": "ORD-74985"}}', '{"name": "search_products", "arguments": {"query": "Sony WH-1000XM5 headphones", "max_price": 7999}}', '{"name": "search_products", "arguments": {"query": "Woodland Leather Boots", "category": "Footwear", "filters": {"material": "leather", "type": "boots"}}}', '{"name": "log_complaint", "arguments": {"order_id": "ORD-62797", "item": "Redmi Note 13 Pro", "complaint": "Charger missing from the box."}}\nI\'ve logged your complaint about the missing charger for order ORD-62797. We will investigate this issue and get back to you shortly.']

In [8]:
tool_response_df = train_df[
    train_df["has_tools"]==True
].copy()

print("Tool-related responses:", len(tool_response_df))

print(
    tool_response_df["response"]
    .head(10)
    .tolist()
)

Tool-related responses: 8735
['{"name": "initiate_exchange", "arguments": {"order_id": "ORD-47172"}}', '{"name": "log_complaint", "arguments": {"order_id": "ORD-59948", "item": "Fluke 117 multimeter", "reason": "stopped working after a week"}}\nI\'ve logged your complaint about the Fluke 117 multimeter from order ORD-59948. We\'ll investigate this issue for you.', '{"name": "log_complaint", "arguments": {"order_id": "ORD-13033", "item": "Razer DeathAdder V3", "issue": "stopped working after only a month"}}\nI\'ve logged a complaint regarding your Razer DeathAdder V3. We\'ll investigate this issue for you.', '{"name": "log_complaint", "arguments": {"order_id": "ORD-76093", "customer_id": "None", "reason": "damaged item", "action_requested": "replacement or refund"}}\nI\'ve logged your complaint about the damaged dumbbell set and requested a replacement or refund. We will investigate this issue and get back to you shortly.', '{"name": "log_complaint", "arguments": {"order_id": "ORD-35252", "complaint": "Book arrived damaged. Customer demands a full refund."}}\nI\'ve logged your complaint regarding the damaged book and your demand for a full refund.', '{"name": "escalate_to_agent", "arguments": {"customer_request": "The customer has specific questions about the fit and ideal activities for the Nike Air Max 270 and would like to chat with a human."}}\nI\'ve escalated your request to a human agent who will be able to help you with your specific questions.', '{"name": "cancel_order", "arguments": {"order_id": "ORD-74985"}}', '{"name": "search_products", "arguments": {"query": "Sony WH-1000XM5 headphones", "max_price": 7999}}', '{"name": "search_products", "arguments": {"query": "Woodland Leather Boots", "category": "Footwear", "filters": {"material": "leather", "type": "boots"}}}', '{"name": "log_complaint", "arguments": {"order_id": "ORD-62797", "item": "Redmi Note 13 Pro", "complaint": "Charger missing from the box."}}\nI\'ve logged your complaint about the missing charger for order ORD-62797. We will investigate this issue and get back to you shortly.']

In [9]:
import json


def extract_tool_call(response):
    if not isinstance(response, str):
        return None

    decoder = json.JSONDecoder()

    # Try every possible JSON-object starting position
    for i, char in enumerate(response):
        if char != "{":
            continue

        try:
            obj, _ = decoder.raw_decode(response[i:])

            if (
                isinstance(obj, dict)
                and "name" in obj
                and "arguments" in obj
            ):
                return obj

        except json.JSONDecodeError:
            continue

    return None


tool_response_df["tool_call"] = (
    tool_response_df["response"]
    .apply(extract_tool_call)
)

print(
    "Successfully parsed:",
    tool_response_df["tool_call"].notna().sum()
)

print(
    "Failed to parse:",
    tool_response_df["tool_call"].isna().sum()
)

Successfully parsed: 1613
Failed to parse: 7122

In [10]:
failed_tool_responses = tool_response_df[
    tool_response_df["tool_call"].isna()
]

for i, response in enumerate(
    failed_tool_responses["response"].head(20),
    1
):
    print("=" * 100)
    print(f"SAMPLE {i}")
    print(repr(response))

====================================================================================================
SAMPLE 1
"Assuredly! I understand that you are seeking information about the situations in which you can request a refund. Let me provide you with a clear breakdown:\n\n1. **Product/Service Defect:** If you find that the product or service you have purchased is defective or does not meet the stated description, you are usually eligible for a refund.\n2. **Cancellation within Grace Period:** If you change your mind and decide to cancel your purchase within the specified grace period, you should be able to receive a refund.\n3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or that appear unfamiliar, we will investigate and assist you in resolving the issue.\n4. **Event Cancellation:** If you have purchased tickets for an event that gets canceled and is not rescheduled, you would typically be eligible for a refund.\n5. **Duplicate Charges:** If you discover that you have been charged multiple times for the same item or service, please notify us so that we can rectify the situation promptly.\n6. **Non-receipt of Goods:** If you have not received your ordered product within the expected delivery time frame, you may qualify for a refund.\n\nPlease keep in mind that refund policies can vary depending on the vendor or service provider. It is always recommended to consult their terms and conditions or directly reach out to them for a comprehensive understanding of their specific policies. If you have any specific concerns or questions related to an order or refund, please provide me with the necessary details, such as the ORD-83197857, and I'll be more than happy to assist you further. Your satisfaction is our top priority.\n\nLet me know if there's anything else I can help you with!"
====================================================================================================
SAMPLE 2
'I can relate to the understanding that you need assistance with canceling your order with the number ORD-91756179. I apologize for any inconvenience this may have caused. To cancel your order, please follow these steps:\n\n1. Sign into your account: Visit our website and log in using your credentials.\n2. Go to your order history: Navigate to the "Order History" or "My Orders" section.\n3. Locate the specific order: Find the order with the number ORD-91756179 in your order history.\n4. Initiate the cancellation: Look for the "Cancel Order" option associated with the order and select it.\n5. Confirm the cancellation: Follow any additional prompts to confirm the cancellation.\n\nIf you encounter any difficulties or have further questions, our dedicated customer support team is available during Monday through Friday, 9 AM to 6 PM EST to assist you. You can reach us at 1-800-555-0147 or utilize the Live Chat feature on our website at https://www.shoparia.com. We value your satisfaction and are here to help you every step of the way.'
====================================================================================================
SAMPLE 3
"We appreciate your message! It's clear to me that you would like to make changes to your order with the number ORD-85345555. I'm here to help you with that. Could you please let me know specifically what changes you would like to make? Whether it's adding, removing, or modifying items, I will do my best to accommodate your request. Your satisfaction is our top priority, and we want to ensure that your order meets your expectations. Please provide me with the details so that I can assist you further."
====================================================================================================
SAMPLE 4
"I apologize for the inconvenience caused. I'm here to assist you with changing your shipping address. To proceed, please provide me with the correct shipping address you would like to update it to."
====================================================================================================
SAMPLE 5
'We understand that you would like to know how to add an article to purchase number ORD-21496211. Making modifications to your purchase is essential, and we\'re here to guide you through the process. To add an article to your purchase, you can follow these simple steps:\n\n1. Go to your account dashboard or the "My Orders" section on our website.\n2. Find the specific purchase with the purchase number ORD-21496211 and click on it to view the details.\n3. Look for an "Edit" or "Modify" option beside the purchase details.\n4. Click on the "Edit" or "Modify" option, which will allow you to make changes to your purchase.\n5. Once you are in the edit mode, you will be able to add or remove articles from your purchase.\n6. Locate the section or button that says "Add Article" or a similar option.\n7. Click on the "Add Article" button, and a search bar or product selection field will appear.\n8. Use the search bar or product selection field to find the specific article you want to add to your purchase by entering its name, SKU, or any other relevant identifier.\n9. Select the desired article from the search results and click on the "Add" button, or follow the provided instructions.\n10. The selected article will now be added to your purchase, and you can proceed with the checkout process.\n\nIf you encounter any difficulties during this process, please don\'t hesitate to reach out to our customer support team by calling 1-800-555-0147. They will be more than happy to assist you further. Remember, we\'re here to ensure your complete satisfaction with your purchase.'
====================================================================================================
SAMPLE 6
"I've realized that you're having difficulty correcting purchase number ORD-43374088. I apologize for any inconvenience this may have caused. To assist you further, could you please provide more details about the specific issue you are facing? This will allow us to better understand the problem and find the most suitable solution for you. Your satisfaction is our top priority, and we are here to help you every step of the way."
====================================================================================================
SAMPLE 7
'We understand that you need assistance with removing several items from your order with order number ORD-84593961. We apologize for any inconvenience this may have caused you. In order to assist you further, could you please provide us with the specific items you would like to remove? This will help us ensure that the necessary changes are made accurately and promptly. Thank you for bringing this to our attention, and we appreciate your patience as we work to resolve this matter for you.'
====================================================================================================
SAMPLE 8
'I recognize that you need guidance on canceling your purchase with the order number ORD-93131979. Let me assist you with the process:\n\n1. Access Your Account: Start by logging into your your ShopAria account using your credentials.\n2. Locate Your Orders: Once logged in, navigate to the "online order management" or "online order management" section.\n3. Find the Specific Purchase: Look for the purchase associated with the order number ORD-93131979 and click on it to view the details.\n4. Initiate the Cancellation: You should find an option labeled "online order management" connected to your purchase. Please select this option.\n5. Follow Any Additional Steps: Depending on the platform, you might be prompted to confirm the cancellation or provide feedback about your cancellation request. Please follow the instructions accordingly.\n\nIf you encounter any difficulties or have further questions during the process, our dedicated team is available to assist you. You can reach us during Monday through Friday, 9 AM to 6 PM EST at 1-800-555-0147 or use the Live Chat feature on our website at https://www.shoparia.com. We appreciate your trust and remain committed to ensuring your satisfaction.'
====================================================================================================
SAMPLE 9
"Of course! I understand your need to verify the specific situations in which you can request a refund. Here is a breakdown of the common situations where you may be eligible for a refund:\n\n1. **Product/Service Defect:** If the product or service you received is defective or does not meet the promised specifications, you usually have the right to request a refund.\n2. **Cancellation within Grace Period:** In case you change your mind or no longer require the product or service, canceling within the specified grace period often entitles you to receive a refund.\n3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or are unfamiliar with, please reach out to us immediately. We will investigate the charges and provide assistance accordingly.\n4. **Event Cancellation:** If you purchased tickets for an event that gets canceled and is not rescheduled, you generally have the option to request a refund.\n5. **Duplicate Charges:** If you have been charged multiple times for the same item or service, please notify us, and we will rectify the situation and process a refund if appropriate.\n6. **Delivery Issues:** If you have not received the ordered product or service within the expected delivery time frame or if the item was not delivered at all, you may be eligible for a refund.\n\nPlease keep in mind that these are general situations, and specific refund policies may vary depending on the vendor or service provider. It's always a good idea to review the terms and conditions or contact the respective party for more detailed information. If you have any specific questions or if there's a particular order you'd like me to look into, please provide the necessary details, such as the order number or relevant information, and I'll be glad to assist you further.\n\nIs there anything else I can help you with?"
====================================================================================================
SAMPLE 10
"I've understood, you need assistance in swapping some products for purchase number ORD-54769200. Our team is here to help you make the necessary changes. Please provide us with the details of the products you would like to swap, including the specific items you want to exchange them with. This will allow us to process your request accurately and efficiently. We are committed to ensuring your complete satisfaction with your purchase. Let us know how we can assist you further."
====================================================================================================
SAMPLE 11
"No problem, I'm here to help! To resolve the issue with updating your address, please follow these steps: \n1. Double-check that you are logged into your account.\n2. Ensure that you have the correct permissions to make address changes.\n3. Try clearing your browser cache and refreshing the page.\nIf the issue persists, please reach out to our customer support team for further assistance."
====================================================================================================
SAMPLE 12
"We're here for you to us for assistance in updating your order with the number ORD-79182797. We understand that sometimes there may be changes or modifications needed for your order, and we're here to help. To ensure we provide you with the most accurate assistance, could you please specify the updates you would like to make? Whether it's adding or removing items, changing quantities, or updating the shipping address, we're here to ensure your order meets your expectations. Please provide us with the details, and we'll work together to make the necessary updates."
====================================================================================================
SAMPLE 13
'We understand that you would like to change a product in order number #ORD-16740197. We apologize for any inconvenience this may have caused. To assist you further, could you please provide us with the details of the product you wish to change? This will enable us to ensure a smooth and accurate modification process. Your satisfaction is our utmost priority, and we appreciate your patience while we address your request.'
====================================================================================================
SAMPLE 14
"For sure! I'm here to assist you with checking the bill with the number #INV-80798. To access the bill, you can log in to your account on our website and navigate to the billing section. There, you should be able to find an option to view your invoices or bills. If you need further guidance or encounter any difficulties, please feel free to let me know. I'm dedicated to making this process as seamless as possible for you."
====================================================================================================
SAMPLE 15
"Unquestionably! I'm here to assist you in understanding the cases in which you can request a refund. Here are some common scenarios:\n\n1. **Product Defect:** If the product you receive is defective or doesn't match its description, you can usually request a refund.\n2. **Canceled Orders:** If you decide to cancel your order within the specified cancellation window, you are often eligible for a refund.\n3. **Unauthorized Charges:** If you notice any charges on your account that you didn't authorize, please let us know so we can investigate and assist you with a refund if necessary.\n4. **Non-Delivery of Goods/Services:** If you don't receive the goods or services you purchased within the expected timeframe, you may be entitled to a refund.\n5. **Duplicate Charges:** If you see duplicate charges on your account for the same item, please reach out to us so we can rectify the situation and issue a refund if appropriate.\n6. **Event Cancellations:** If an event is canceled and not rescheduled, you should typically be able to obtain a refund for your ticket.\n\nPlease keep in mind that these are general guidelines, and specific refund policies may vary depending on the vendor or service provider. It's always recommended to review the terms and conditions or contact the provider directly for more detailed information.\n\nIf you have any specific questions or concerns about a particular order or refund, please provide me with the relevant details, such as the order number or any other pertinent information, and I'll be happy to assist you further."
====================================================================================================
SAMPLE 16
"Certainly! I'm here to assist you in canceling purchase ORD-20993268. Let's proceed together to make sure everything goes smoothly:\n\n1. **Access Your Account**: Begin by logging into your https://www.shoparia.com.\n2. **Find Your Orders**: Once logged in, navigate to the 'online order management' or 'online order management' section.\n3. **Locate Your Purchase**: Look for the specific purchase associated with the order number ORD-20993268 and click on it.\n4. **Cancel Your Order**: You will find an option labeled 'online order management' linked to this purchase. Please select it.\n5. **Complete the Process**: Our system may require some additional information or confirmation. Kindly provide any necessary details to complete the cancellation.\n\nIf you encounter any difficulties or need further assistance, please don't hesitate to reach out to our dedicated support team. You can contact them during Monday through Friday, 9 AM to 6 PM EST at 1-800-555-0147 or utilize the Live Chat feature on our https://www.shoparia.com. We appreciate your trust in us, and ensuring your satisfaction is our utmost priority."
====================================================================================================
SAMPLE 17
"Indeed! I understand how important it is for you to locate the bill associated with Mr. King. To assist you effectively, could you please provide me with any relevant information such as the date range, invoice number, or any other details you might have? With this additional information, I'll be able to help you locate the specific bill efficiently."
====================================================================================================
SAMPLE 18
'I apologize for any confusion. To update your shipping address, please follow these steps: \n\n1. Log in to your account on our website/app.\n2. Go to the "My Account" or "Profile" section.\n3. Look for the "Shipping Address" or "Delivery Information" tab.\n4. Click on it to edit your current address.\n5. Make the necessary changes and click on the "Save" or "Update" button.\n\nIf you encounter any difficulties or need further assistance, please don\'t hesitate to contact our customer support.'
====================================================================================================
SAMPLE 19
"Of course! Let's explore the situations in which you can request a refund. Rest assured, we prioritize your satisfaction and aim to make the refund process as seamless as possible. Here are some common scenarios where you may be eligible for a refund:\n\n1. **Product/Service Defect:** If the product you purchased has a defect or doesn't match the description, you can typically request a refund.\n\n2. **Late Delivery or Non-Delivery:** If your order hasn't arrived within the expected timeframe, or if it hasn't been delivered at all, we understand your concerns and will work with you to find a suitable solution, which may include a refund.\n\n3. **Cancellation within Grace Period:** Should you change your mind about a purchase and notify us within the designated grace period, you can often request a refund.\n\n4. **Unauthorized Charges:** If you notice any charges on your account that you didn't authorize, please alert us immediately. We'll investigate the issue and, if necessary, process a refund.\n\n5. **Service Dissatisfaction:** Your satisfaction is our utmost priority. If you're dissatisfied with a service you received from us, please reach out so we can address your concerns and find an appropriate resolution, which may include a refund.\n\nPlease keep in mind that each situation may have its specific requirements and terms, so I recommend reviewing our comprehensive refund policy or contacting our customer support team for personalized assistance. They can provide you with detailed information based on the specific circumstances of your request.\n\nI hope this clarifies the situations in which you can request a refund. If you have any further questions or need assistance with a specific refund request, please don't hesitate to reach out."
====================================================================================================
SAMPLE 20
"I understood, you're unable to check our money back guarantee. Allow me to provide you with the necessary information. Our money back guarantee ensures that if you are dissatisfied with our product or service within a specified timeframe, you can request a refund. However, please note that certain conditions may apply, such as returning the product in its original condition or canceling the service within a specific period. To get detailed information about our money back guarantee and its specific requirements, I recommend visiting our website or contacting our customer support team. They will be more than happy to clarify any doubts you may have and guide you through the refund process. Don't hesitate to reach out if you need any further assistance."

In [ ]:
print(
    failed_tool_responses["response"]
    .str.len()
    .describe()
)

count    7122.000000
mean      819.122016
std       444.913947
min        44.000000
25%       449.000000
50%       757.500000
75%      1079.000000
max      2472.000000
Name: response, dtype: float64

In [ ]:
tool_response_df[
    tool_response_df["tool_call"].notna()
][["response", "tool_call"]].head(10).to_string(index=False)

'                                                                                                                                                                                                                                                                                                                     response                                                                                                                                                                                                tool_call\n                                                                                                                                                                                                                                                        {"name": "initiate_exchange", "arguments": {"order_id": "ORD-47172"}}                                                                                                                                    {\'name\': \'initiate_exchange\', \'arguments\': {\'order_id\': \'ORD-47172\'}}\n                                                           {"name": "log_complaint", "arguments": {"order_id": "ORD-59948", "item": "Fluke 117 multimeter", "reason": "stopped working after a week"}}\\nI\'ve logged your complaint about the Fluke 117 multimeter from order ORD-59948. We\'ll investigate this issue for you.                                                              {\'name\': \'log_complaint\', \'arguments\': {\'order_id\': \'ORD-59948\', \'item\': \'Fluke 117 multimeter\', \'reason\': \'stopped working after a week\'}}\n                                                                           {"name": "log_complaint", "arguments": {"order_id": "ORD-13033", "item": "Razer DeathAdder V3", "issue": "stopped working after only a month"}}\\nI\'ve logged a complaint regarding your Razer DeathAdder V3. We\'ll investigate this issue for you.                                                          {\'name\': \'log_complaint\', \'arguments\': {\'order_id\': \'ORD-13033\', \'item\': \'Razer DeathAdder V3\', \'issue\': \'stopped working after only a month\'}}\n{"name": "log_complaint", "arguments": {"order_id": "ORD-76093", "customer_id": "None", "reason": "damaged item", "action_requested": "replacement or refund"}}\\nI\'ve logged your complaint about the damaged dumbbell set and requested a replacement or refund. We will investigate this issue and get back to you shortly.                                          {\'name\': \'log_complaint\', \'arguments\': {\'order_id\': \'ORD-76093\', \'customer_id\': \'None\', \'reason\': \'damaged item\', \'action_requested\': \'replacement or refund\'}}\n                                                                                            {"name": "log_complaint", "arguments": {"order_id": "ORD-35252", "complaint": "Book arrived damaged. Customer demands a full refund."}}\\nI\'ve logged your complaint regarding the damaged book and your demand for a full refund.                                                                  {\'name\': \'log_complaint\', \'arguments\': {\'order_id\': \'ORD-35252\', \'complaint\': \'Book arrived damaged. Customer demands a full refund.\'}}\n            {"name": "escalate_to_agent", "arguments": {"customer_request": "The customer has specific questions about the fit and ideal activities for the Nike Air Max 270 and would like to chat with a human."}}\\nI\'ve escalated your request to a human agent who will be able to help you with your specific questions. {\'name\': \'escalate_to_agent\', \'arguments\': {\'customer_request\': \'The customer has specific questions about the fit and ideal activities for the Nike Air Max 270 and would like to chat with a human.\'}}\n                                                                                                                                                                                                                                                             {"name": "cancel_order", "arguments": {"order_id": "ORD-74985"}}                                                                                                                                         {\'name\': \'cancel_order\', \'arguments\': {\'order_id\': \'ORD-74985\'}}\n                                                                                                                                                                                                                         {"name": "search_products", "arguments": {"query": "Sony WH-1000XM5 headphones", "max_price": 7999}}                                                                                                     {\'name\': \'search_products\', \'arguments\': {\'query\': \'Sony WH-1000XM5 headphones\', \'max_price\': 7999}}\n                                          {"name": "log_complaint", "arguments": {"order_id": "ORD-62797", "item": "Redmi Note 13 Pro", "complaint": "Charger missing from the box."}}\\nI\'ve logged your complaint about the missing charger for order ORD-62797. We will investigate this issue and get back to you shortly.                                                             {\'name\': \'log_complaint\', \'arguments\': {\'order_id\': \'ORD-62797\', \'item\': \'Redmi Note 13 Pro\', \'complaint\': \'Charger missing from the box.\'}}\n                                                                                                                                                                        {"name": "initiate_return", "arguments": {"order_id": "ORD-80458", "reason": "Not quite what I was looking for", "item_sku": "Makita angle grinder"}}                                                    {\'name\': \'initiate_return\', \'arguments\': {\'order_id\': \'ORD-80458\', \'reason\': \'Not quite what I was looking for\', \'item_sku\': \'Makita angle grinder\'}}'

In [ ]:
failed_tool_responses = tool_response_df[
    tool_response_df["tool_call"].isna()
]

print(
    failed_tool_responses[
        ["response_type", "response"]
    ].head(20).to_string(index=False)
)

response_type                                                                                                                                                                                                                       response
    tool_call                                                                     {"name": "search_products", "arguments": {"query": "Woodland Leather Boots", "category": "Footwear", "filters": {"material": "leather", "type": "boots"}}}
    tool_call                                                                              {"name": "search_products", "arguments": {"query": "Campingaz Camping Stove", "category": "garden & outdoor", "filters": {"brand": "Campingaz"}}}
    tool_call                                                                                                                     {"name": "search_products", "arguments": {"query": "scratching post", "filters": {"brand": "Paws India"}}}
    tool_call                                                                                                        {"name": "search_products", "arguments": {"query": "Adidas Ultraboost 22 running shoes", "filters": {"gender": "men"}}}
    tool_call                                                                                                                     {"name": "search_products", "arguments": {"query": "Fluke 117 Multimeter", "filters": {"brand": "Fluke"}}}
    tool_call                                                                                                                                 {"name": "search_products", "arguments": {"query": "football", "filters": {"brand": "Cosco"}}}
    tool_call                                                                                                    {"name": "search_products", "arguments": {"query": "Flower Mix", "category": "Seeds", "filters": {"brand": "Kraft Seeds"}}}
    tool_call I understand you're looking for Makita Angle Grinders from the industrial series. I can help you with that.\n{"name": "search_products", "arguments": {"query": "Makita Angle Grinders", "filters": {"series": "industrial"}}}
    tool_call                                                                                                                       {"name": "search_products", "arguments": {"query": "running shorts", "filters": {"brand": "Decathlon"}}}
    tool_call                                                                                                  {"name": "search_products", "arguments": {"query": "Minimalist 2% Salicylic Acid Serum", "filters": {"brand": "Minimalist"}}}
    tool_call                                                                              {"name": "search_products", "arguments": {"query": "knife set", "category": "kitchen", "max_price": 4999, "filters": {"brand": "Amazon Basics"}}}
    tool_call                                                                                                  {"name": "search_products", "arguments": {"query": "PlayStation 5", "category": "Electronics", "filters": {"brand": "Sony"}}}
    tool_call                                                                          {"name": "search_products", "arguments": {"query": "garden chair set", "category": "furniture", "max_price": 9999, "filters": {"brand": "Nilkamal"}}}
    tool_call                                                                                                                    {"name": "search_products", "arguments": {"query": "face wash", "filters": {"brand": "Forest Essentials"}}}
    tool_call                                                                                                        {"name": "search_products", "arguments": {"query": "yoga mat", "category": "Fitness", "filters": {"brand": "Boldfit"}}}
    tool_call                                                                                              {"name": "search_products", "arguments": {"query": "face wash", "category": "Beauty", "filters": {"brand": "Forest Essentials"}}}
    tool_call                                                                      {"name": "search_products", "arguments": {"query": "running shorts", "category": "sporting goods", "max_price": 2999, "filters": {"brand": "Decathlon"}}}
    tool_call                                                                                                                        {"name": "search_products", "arguments": {"query": "Trixie Dog Leash", "filters": {"brand": "Trixie"}}}
    tool_call                                                                      {"name": "search_products", "arguments": {"query": "badminton racket", "category": "Sports & Outdoors", "max_price": 999, "filters": {"brand": "Nivia"}}}
    tool_call                                                                                      {"name": "search_products", "arguments": {"query": "Makita angle grinder", "max_price": 7999, "filters": {"intended_use": "industrial"}}}

In [ ]:
print(
    failed_tool_responses["response_type"].value_counts()
)

response_type
tool_call    6351
mixed         806
Name: count, dtype: int64

In [11]:
# Content-based tool-call detection using the parsed results

tool_call_in_response = tool_response_df["tool_call"].notna()

print(
    pd.crosstab(
        tool_response_df["response_type"],
        tool_call_in_response,
        margins=True
    )
)

tool_call      False  True   All
response_type
mixed            806   400  1206
tool_call       6316  1213  7529
All             7122  1613  8735

In [ ]:
tool_response_df.head()

,id,source,group,difficulty,system,history,prompt,context,tools,response_type,...,domain,intent_category,intent,sub_intent,capability,test_tier,tools_parsed,has_tools,tool_names,tool_call
0,ecomm_65b14bfa,synthetic_api_generated,A,2,"You are Aria, a helpful e-commerce assistant. ...",[],"Hey there, I just got my Dyson V12 vacuum clea...","{""retrieved_docs"": [], ""user_profile"": {}, ""ca...","[{""type"": ""function"", ""function"": {""name"": ""in...",tool_call,...,appliances,returns_exchanges,exchange_request,variant_swap,exchange_request,,"[{'type': 'function', 'function': {'name': 'in...",True,[initiate_exchange],"{'name': 'initiate_exchange', 'arguments': {'o..."
2,ecomm_aea26126,synthetic_api_generated,C,2,"You are Aria, a helpful e-commerce assistant. ...",[],"Hey, my Fluke 117 multimeter from order ORD-59...","{""retrieved_docs"": [], ""user_profile"": {}, ""ca...","[{""type"": ""function"", ""function"": {""name"": ""lo...",mixed,...,industrial,customer_support,complaint_handling,escalation_request,complaint_handling,,"[{'type': 'function', 'function': {'name': 'lo...",True,[log_complaint],"{'name': 'log_complaint', 'arguments': {'order..."
3,ecomm_6980dde2,synthetic_api_generated,C,2,"You are Aria, a helpful e-commerce assistant. ...",[],"Hey, my Razer DeathAdder V3 just stopped worki...","{""retrieved_docs"": [], ""user_profile"": {}, ""ca...","[{""type"": ""function"", ""function"": {""name"": ""lo...",mixed,...,gaming,customer_support,complaint_handling,escalation_request,complaint_handling,,"[{'type': 'function', 'function': {'name': 'lo...",True,[log_complaint],"{'name': 'log_complaint', 'arguments': {'order..."
5,ecomm_946c42b8,synthetic_api_generated,C,2,"You are Aria, a helpful e-commerce assistant. ...",[],"Hey, my dumbbell set (ORD-76093) arrived damag...","{""retrieved_docs"": [], ""user_profile"": {}, ""ca...","[{""type"": ""function"", ""function"": {""name"": ""lo...",mixed,...,sports_outdoors,customer_support,complaint_handling,escalation_request,complaint_handling,,"[{'type': 'function', 'function': {'name': 'lo...",True,[log_complaint],"{'name': 'log_complaint', 'arguments': {'order..."
7,ecomm_f02cf99c,synthetic_api_generated,C,3,"You are Aria, a helpful e-commerce assistant. ...","[{""role"": ""user"", ""content"": ""I'm seriously an...",The book arrived damaged! I demand a full refu...,"{""retrieved_docs"": [], ""user_profile"": {""name""...","[{""type"": ""function"", ""function"": {""name"": ""lo...",mixed,...,books_media,customer_support,complaint_handling,escalation_request,complaint_handling,,"[{'type': 'function', 'function': {'name': 'lo...",True,[log_complaint],"{'name': 'log_complaint', 'arguments': {'order..."

In [12]:
# Inspect the 7,122 records that have tool metadata
# but where our parser did not detect a tool call in the response.

no_detected_tool = tool_response_df[
    tool_response_df["tool_call"].isna()
].copy()

print("Rows:", len(no_detected_tool))

print("\nResponse types:")
print(no_detected_tool["response_type"].value_counts())

print("\nResponse length:")
print(no_detected_tool["response"].str.len().describe())

print("\nSample responses:")
for i, row in no_detected_tool.head(30).iterrows():
    print("=" * 100)
    print("prompt:", row["prompt"])
    print("response_type:", row["response_type"])
    print("intent:", row["intent"])
    print("sub_intent:", row["sub_intent"])
    print("tool schema:", row["tools"])
    print("\nRESPONSE:")
    print(row["response"])

Rows: 7122

Response types:
response_type
tool_call    6316
mixed         806
Name: count, dtype: int64

Response length:
count    7122.000000
mean      819.122016
std       444.913947
min        44.000000
25%       449.000000
50%       757.500000
75%      1079.000000
max      2472.000000
Name: response, dtype: float64

Sample responses:
====================================================================================================
prompt: help me see in which situations cani ask to be refunded
response_type: tool_call
intent: return_refund
sub_intent: refund_eligibility
tool schema: [{"type": "function", "function": {"name": "initiate_return", "description": "Initiate a return and generate a return label", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}, "item_sku": {"type": "string"}}, "required": ["order_id", "reason"]}}}]

RESPONSE:
Assuredly! I understand that you are seeking information about the situations in which you can request a refund. Let me provide you with a clear breakdown:

1. **Product/Service Defect:** If you find that the product or service you have purchased is defective or does not meet the stated description, you are usually eligible for a refund.
2. **Cancellation within Grace Period:** If you change your mind and decide to cancel your purchase within the specified grace period, you should be able to receive a refund.
3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or that appear unfamiliar, we will investigate and assist you in resolving the issue.
4. **Event Cancellation:** If you have purchased tickets for an event that gets canceled and is not rescheduled, you would typically be eligible for a refund.
5. **Duplicate Charges:** If you discover that you have been charged multiple times for the same item or service, please notify us so that we can rectify the situation promptly.
6. **Non-receipt of Goods:** If you have not received your ordered product within the expected delivery time frame, you may qualify for a refund.

Please keep in mind that refund policies can vary depending on the vendor or service provider. It is always recommended to consult their terms and conditions or directly reach out to them for a comprehensive understanding of their specific policies. If you have any specific concerns or questions related to an order or refund, please provide me with the necessary details, such as the ORD-83197857, and I'll be more than happy to assist you further. Your satisfaction is our top priority.

Let me know if there's anything else I can help you with!
====================================================================================================
prompt: cance order ORD-91756179
response_type: tool_call
intent: order_cancellation
sub_intent: cancel_before_shipment
tool schema: [{"type": "function", "function": {"name": "cancel_order", "description": "Cancel an order if within the cancellation window", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
I can relate to the understanding that you need assistance with canceling your order with the number ORD-91756179. I apologize for any inconvenience this may have caused. To cancel your order, please follow these steps:

1. Sign into your account: Visit our website and log in using your credentials.
2. Go to your order history: Navigate to the "Order History" or "My Orders" section.
3. Locate the specific order: Find the order with the number ORD-91756179 in your order history.
4. Initiate the cancellation: Look for the "Cancel Order" option associated with the order and select it.
5. Confirm the cancellation: Follow any additional prompts to confirm the cancellation.

If you encounter any difficulties or have further questions, our dedicated customer support team is available during Monday through Friday, 9 AM to 6 PM EST to assist you. You can reach us at 1-800-555-0147 or utilize the Live Chat feature on our website at https://www.shoparia.com. We value your satisfaction and are here to help you every step of the way.
====================================================================================================
prompt: change  order ORD-85345555
response_type: tool_call
intent: exchange_request
sub_intent: order_modification
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
We appreciate your message! It's clear to me that you would like to make changes to your order with the number ORD-85345555. I'm here to help you with that. Could you please let me know specifically what changes you would like to make? Whether it's adding, removing, or modifying items, I will do my best to accommodate your request. Your satisfaction is our top priority, and we want to ensure that your order meets your expectations. Please provide me with the details so that I can assist you further.
====================================================================================================
prompt: I submitted a wrong shipping address, I awnt to change it
response_type: mixed
intent: account_management
sub_intent: address_management
tool schema: [{"type": "function", "function": {"name": "update_account", "description": "Update user account details", "parameters": {"type": "object", "properties": {"user_id": {"type": "string"}, "field": {"type": "string", "enum": ["shipping_address", "email", "phone", "password"]}, "value": {"type": "string"}}, "required": ["user_id", "field", "value"]}}}]

RESPONSE:
I apologize for the inconvenience caused. I'm here to assist you with changing your shipping address. To proceed, please provide me with the correct shipping address you would like to update it to.
====================================================================================================
prompt: how to add an article to purchase ORD-21496211?
response_type: tool_call
intent: exchange_request
sub_intent: order_modification
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
We understand that you would like to know how to add an article to purchase number ORD-21496211. Making modifications to your purchase is essential, and we're here to guide you through the process. To add an article to your purchase, you can follow these simple steps:

1. Go to your account dashboard or the "My Orders" section on our website.
2. Find the specific purchase with the purchase number ORD-21496211 and click on it to view the details.
3. Look for an "Edit" or "Modify" option beside the purchase details.
4. Click on the "Edit" or "Modify" option, which will allow you to make changes to your purchase.
5. Once you are in the edit mode, you will be able to add or remove articles from your purchase.
6. Locate the section or button that says "Add Article" or a similar option.
7. Click on the "Add Article" button, and a search bar or product selection field will appear.
8. Use the search bar or product selection field to find the specific article you want to add to your purchase by entering its name, SKU, or any other relevant identifier.
9. Select the desired article from the search results and click on the "Add" button, or follow the provided instructions.
10. The selected article will now be added to your purchase, and you can proceed with the checkout process.

If you encounter any difficulties during this process, please don't hesitate to reach out to our customer support team by calling 1-800-555-0147. They will be more than happy to assist you further. Remember, we're here to ensure your complete satisfaction with your purchase.
====================================================================================================
prompt: i cant correct purchase ORD-43374088
response_type: tool_call
intent: exchange_request
sub_intent: exchange_different_item
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
I've realized that you're having difficulty correcting purchase number ORD-43374088. I apologize for any inconvenience this may have caused. To assist you further, could you please provide more details about the specific issue you are facing? This will allow us to better understand the problem and find the most suitable solution for you. Your satisfaction is our top priority, and we are here to help you every step of the way.
====================================================================================================
prompt: need help removing several items from order ORD-84593961
response_type: tool_call
intent: exchange_request
sub_intent: order_modification
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
We understand that you need assistance with removing several items from your order with order number ORD-84593961. We apologize for any inconvenience this may have caused you. In order to assist you further, could you please provide us with the specific items you would like to remove? This will help us ensure that the necessary changes are made accurately and promptly. Thank you for bringing this to our attention, and we appreciate your patience as we work to resolve this matter for you.
====================================================================================================
prompt: what do I have to do to cancel purchase ORD-93131979?
response_type: tool_call
intent: order_cancellation
sub_intent: cancel_before_shipment
tool schema: [{"type": "function", "function": {"name": "cancel_order", "description": "Cancel an order if within the cancellation window", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
I recognize that you need guidance on canceling your purchase with the order number ORD-93131979. Let me assist you with the process:

1. Access Your Account: Start by logging into your your ShopAria account using your credentials.
2. Locate Your Orders: Once logged in, navigate to the "online order management" or "online order management" section.
3. Find the Specific Purchase: Look for the purchase associated with the order number ORD-93131979 and click on it to view the details.
4. Initiate the Cancellation: You should find an option labeled "online order management" connected to your purchase. Please select this option.
5. Follow Any Additional Steps: Depending on the platform, you might be prompted to confirm the cancellation or provide feedback about your cancellation request. Please follow the instructions accordingly.

If you encounter any difficulties or have further questions during the process, our dedicated team is available to assist you. You can reach us during Monday through Friday, 9 AM to 6 PM EST at 1-800-555-0147 or use the Live Chat feature on our website at https://www.shoparia.com. We appreciate your trust and remain committed to ensuring your satisfaction.
====================================================================================================
prompt: help checking in which situations can I ask for a refund
response_type: tool_call
intent: return_refund
sub_intent: refund_eligibility
tool schema: [{"type": "function", "function": {"name": "initiate_return", "description": "Initiate a return and generate a return label", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}, "item_sku": {"type": "string"}}, "required": ["order_id", "reason"]}}}]

RESPONSE:
Of course! I understand your need to verify the specific situations in which you can request a refund. Here is a breakdown of the common situations where you may be eligible for a refund:

1. **Product/Service Defect:** If the product or service you received is defective or does not meet the promised specifications, you usually have the right to request a refund.
2. **Cancellation within Grace Period:** In case you change your mind or no longer require the product or service, canceling within the specified grace period often entitles you to receive a refund.
3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or are unfamiliar with, please reach out to us immediately. We will investigate the charges and provide assistance accordingly.
4. **Event Cancellation:** If you purchased tickets for an event that gets canceled and is not rescheduled, you generally have the option to request a refund.
5. **Duplicate Charges:** If you have been charged multiple times for the same item or service, please notify us, and we will rectify the situation and process a refund if appropriate.
6. **Delivery Issues:** If you have not received the ordered product or service within the expected delivery time frame or if the item was not delivered at all, you may be eligible for a refund.

Please keep in mind that these are general situations, and specific refund policies may vary depending on the vendor or service provider. It's always a good idea to review the terms and conditions or contact the respective party for more detailed information. If you have any specific questions or if there's a particular order you'd like me to look into, please provide the necessary details, such as the order number or relevant information, and I'll be glad to assist you further.

Is there anything else I can help you with?
====================================================================================================
prompt: I have to swap some products of purchase ORD-54769200
response_type: tool_call
intent: exchange_request
sub_intent: order_modification
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
I've understood, you need assistance in swapping some products for purchase number ORD-54769200. Our team is here to help you make the necessary changes. Please provide us with the details of the products you would like to swap, including the specific items you want to exchange them with. This will allow us to process your request accurately and efficiently. We are committed to ensuring your complete satisfaction with your purchase. Let us know how we can assist you further.
====================================================================================================
prompt: i have a trouble updating my addrses
response_type: mixed
intent: account_management
sub_intent: address_management
tool schema: [{"type": "function", "function": {"name": "update_account", "description": "Update user account details", "parameters": {"type": "object", "properties": {"user_id": {"type": "string"}, "field": {"type": "string", "enum": ["shipping_address", "email", "phone", "password"]}, "value": {"type": "string"}}, "required": ["user_id", "field", "value"]}}}]

RESPONSE:
No problem, I'm here to help! To resolve the issue with updating your address, please follow these steps:
1. Double-check that you are logged into your account.
2. Ensure that you have the correct permissions to make address changes.
3. Try clearing your browser cache and refreshing the page.
If the issue persists, please reach out to our customer support team for further assistance.
====================================================================================================
prompt: I want help to update order ORD-79182797
response_type: tool_call
intent: exchange_request
sub_intent: order_modification
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
We're here for you to us for assistance in updating your order with the number ORD-79182797. We understand that sometimes there may be changes or modifications needed for your order, and we're here to help. To ensure we provide you with the most accurate assistance, could you please specify the updates you would like to make? Whether it's adding or removing items, changing quantities, or updating the shipping address, we're here to ensure your order meets your expectations. Please provide us with the details, and we'll work together to make the necessary updates.
====================================================================================================
prompt: I want to change a product of order ORD-16740197
response_type: tool_call
intent: exchange_request
sub_intent: order_modification
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
We understand that you would like to change a product in order number #ORD-16740197. We apologize for any inconvenience this may have caused. To assist you further, could you please provide us with the details of the product you wish to change? This will enable us to ensure a smooth and accurate modification process. Your satisfaction is our utmost priority, and we appreciate your patience while we address your request.
====================================================================================================
prompt: how to check the bill #00108?
response_type: tool_call
intent: order_status
sub_intent: track_order
tool schema: [{"type": "function", "function": {"name": "get_order_status", "description": "Fetch live order status and tracking info", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "user_id": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
For sure! I'm here to assist you with checking the bill with the number #INV-80798. To access the bill, you can log in to your account on our website and navigate to the billing section. There, you should be able to find an option to view your invoices or bills. If you need further guidance or encounter any difficulties, please feel free to let me know. I'm dedicated to making this process as seamless as possible for you.
====================================================================================================
prompt: help me check in which cvases can i ask for my money back
response_type: tool_call
intent: return_refund
sub_intent: refund_eligibility

In [13]:
# Inspect the 1613 records that have tool metadata
# but where our parser did not detect a tool call in the response.

detected_tool = tool_response_df[
    tool_response_df["tool_call"].notna()
].copy()

print("Rows:", len(detected_tool))

print("\nResponse types:")
print(detected_tool["response_type"].value_counts())

print("\nResponse length:")
print(detected_tool["response"].str.len().describe())

print("\nSample responses:")
for i, row in detected_tool.head(30).iterrows():
    print("=" * 100)
    print("prompt:", row["prompt"])
    print("response_type:", row["response_type"])
    print("intent:", row["intent"])
    print("sub_intent:", row["sub_intent"])
    print("tool schema:", row["tools"])
    print("\nRESPONSE:")
    print(row["response"])

Rows: 1613

Response types:
response_type
tool_call    1213
mixed         400
Name: count, dtype: int64

Response length:
count    1613.000000
mean      150.313081
std       105.719257
min        43.000000
25%        79.000000
50%       104.000000
75%       171.000000
max       800.000000
Name: response, dtype: float64

Sample responses:
====================================================================================================
prompt: Hey there, I just got my Dyson V12 vacuum cleaner (order #ORD-47172) and it's not really what I was expecting. Is there a way to exchange it for a different model?
response_type: tool_call
intent: exchange_request
sub_intent: variant_swap
tool schema: [{"type": "function", "function": {"name": "initiate_exchange", "description": "Exchange an item for a different size or variant", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "item_sku": {"type": "string"}, "new_variant": {"type": "string"}}, "required": ["order_id", "item_sku", "new_variant"]}}}]

RESPONSE:
{"name": "initiate_exchange", "arguments": {"order_id": "ORD-47172"}}
====================================================================================================
prompt: Hey, my Fluke 117 multimeter from order ORD-59948 just stopped working after a week. What do I do now?
response_type: mixed
intent: complaint_handling
sub_intent: escalation_request
tool schema: [{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

RESPONSE:
{"name": "log_complaint", "arguments": {"order_id": "ORD-59948", "item": "Fluke 117 multimeter", "reason": "stopped working after a week"}}
I've logged your complaint about the Fluke 117 multimeter from order ORD-59948. We'll investigate this issue for you.
====================================================================================================
prompt: Hey, my Razer DeathAdder V3 just stopped working after only a month! My order ID is ORD-13033, can you help me out?
response_type: mixed
intent: complaint_handling
sub_intent: escalation_request
tool schema: [{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

RESPONSE:
{"name": "log_complaint", "arguments": {"order_id": "ORD-13033", "item": "Razer DeathAdder V3", "issue": "stopped working after only a month"}}
I've logged a complaint regarding your Razer DeathAdder V3. We'll investigate this issue for you.
====================================================================================================
prompt: Hey, my dumbbell set (ORD-76093) arrived damaged. Can I get a replacement or a refund?
response_type: mixed
intent: complaint_handling
sub_intent: escalation_request
tool schema: [{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

RESPONSE:
{"name": "log_complaint", "arguments": {"order_id": "ORD-76093", "customer_id": "None", "reason": "damaged item", "action_requested": "replacement or refund"}}
I've logged your complaint about the damaged dumbbell set and requested a replacement or refund. We will investigate this issue and get back to you shortly.
====================================================================================================
prompt: The book arrived damaged! I demand a full refund immediately!
response_type: mixed
intent: complaint_handling
sub_intent: escalation_request
tool schema: [{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

RESPONSE:
{"name": "log_complaint", "arguments": {"order_id": "ORD-35252", "complaint": "Book arrived damaged. Customer demands a full refund."}}
I've logged your complaint regarding the damaged book and your demand for a full refund.
====================================================================================================
prompt: Yeah, I have some pretty specific questions about the fit and ideal activities for them, could I chat with a human please?
response_type: mixed
intent: human_handoff
sub_intent: agent_transfer
tool schema: [{"type": "function", "function": {"name": "escalate_to_agent", "description": "Transfer conversation to a live human agent", "parameters": {"type": "object", "properties": {"reason": {"type": "string"}, "priority": {"type": "string", "enum": ["low", "medium", "high", "urgent"]}, "context_summary": {"type": "string"}}, "required": ["reason", "priority"]}}}]

RESPONSE:
{"name": "escalate_to_agent", "arguments": {"customer_request": "The customer has specific questions about the fit and ideal activities for the Nike Air Max 270 and would like to chat with a human."}}
I've escalated your request to a human agent who will be able to help you with your specific questions.
====================================================================================================
prompt: Hey, can I cancel my order for the Trixie Dog Leash? The order ID is ORD-74985.
response_type: tool_call
intent: order_cancellation
sub_intent: cancel_before_ship
tool schema: [{"type": "function", "function": {"name": "cancel_order", "description": "Cancel an order if within the cancellation window", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
{"name": "cancel_order", "arguments": {"order_id": "ORD-74985"}}
====================================================================================================
prompt: Hey, I'm looking for the Sony WH-1000XM5 headphones but my budget is around ₹7999. Do you have anything like that?
response_type: tool_call
intent: product_search
sub_intent: brand_filter
tool schema: [{"type": "function", "function": {"name": "search_products", "description": "Search the product catalog with filters", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "category": {"type": "string"}, "max_price": {"type": "number"}, "filters": {"type": "object"}}, "required": ["query"]}}}]

RESPONSE:
{"name": "search_products", "arguments": {"query": "Sony WH-1000XM5 headphones", "max_price": 7999}}
====================================================================================================
prompt: Good morning. I am interested in purchasing a new pair of leather boots and have heard good things about the Woodland brand. Could you please provide me with information regarding available styles, sizes, and color options for Woodland Leather Boots? I am looking for a durable and stylish pair suitable for everyday wear.
response_type: tool_call
intent: product_search
sub_intent: keyword_search
tool schema: [{"type": "function", "function": {"name": "search_products", "description": "Search the product catalog with filters", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "category": {"type": "string"}, "max_price": {"type": "number"}, "filters": {"type": "object"}}, "required": ["query"]}}}]

RESPONSE:
{"name": "search_products", "arguments": {"query": "Woodland Leather Boots", "category": "Footwear", "filters": {"material": "leather", "type": "boots"}}}
====================================================================================================
prompt: Hey, my Redmi Note 13 Pro arrived today (ORD-62797) but the charger is missing from the box. What can I do about this?
response_type: mixed
intent: complaint_handling
sub_intent: complaint_filed
tool schema: [{"type": "function", "function": {"name": "log_complaint", "description": "Log a customer complaint and optionally escalate", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue": {"type": "string"}, "severity": {"type": "string", "enum": ["low", "medium", "high"]}}, "required": ["issue", "severity"]}}}]

RESPONSE:
{"name": "log_complaint", "arguments": {"order_id": "ORD-62797", "item": "Redmi Note 13 Pro", "complaint": "Charger missing from the box."}}
I've logged your complaint about the missing charger for order ORD-62797. We will investigate this issue and get back to you shortly.
====================================================================================================
prompt: Hey, I need to return the Makita angle grinder I ordered (ORD-80458). It's not quite what I was looking for.
response_type: tool_call
intent: return_refund
sub_intent: refund_timeline
tool schema: [{"type": "function", "function": {"name": "initiate_return", "description": "Initiate a return and generate a return label", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}, "item_sku": {"type": "string"}}, "required": ["order_id", "reason"]}}}]

RESPONSE:
{"name": "initiate_return", "arguments": {"order_id": "ORD-80458", "reason": "Not quite what I was looking for", "item_sku": "Makita angle grinder"}}
====================================================================================================
prompt: Hey, just wondering about my Philips Air Purifier, order ID ORD-18996. Has it shipped yet?
response_type: tool_call
intent: order_status
sub_intent: eta_query
tool schema: [{"type": "function", "function": {"name": "get_order_status", "description": "Fetch live order status and tracking info", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "user_id": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
{"name": "get_order_status", "arguments": {"order_id": "ORD-18996"}}
====================================================================================================
prompt: Hey, I'm looking for a new mountain bike. I'm a beginner and I'd prefer something around $700. Any suggestions?
response_type: tool_call
intent: personalized_recommendations
sub_intent: based_on_history
tool schema: [{"type": "function", "function": {"name": "get_recommendations", "description": "Get personalised product recommendations", "parameters": {"type": "object", "properties": {"user_id": {"type": "string"}, "category": {"type": "string"}, "limit": {"type": "integer"}}, "required": ["user_id"]}}}]

RESPONSE:
{"name": "get_recommendations", "arguments": {"category": "mountain bike"}}
====================================================================================================
prompt: Yeah, can you find me a Trixie dog leash?
response_type: tool_call
intent: product_search
sub_intent: price_filter
tool schema: [{"type": "function", "function": {"name": "search_products", "description": "Search the product catalog with filters", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "category": {"type": "string"}, "max_price": {"type": "number"}, "filters": {"type": "object"}}, "required": ["query"]}}}]

RESPONSE:
{"name": "search_products", "arguments": {"query": "Trixie dog leash"}}
====================================================================================================
prompt: I need to return the Stanley 94-248 Tool Kit from order ORD-70404 and get a refund.
response_type: tool_call
intent: return_refund
sub_intent: refund_timeline
tool schema: [{"type": "function", "function": {"name": "initiate_return", "description": "Initiate a return and generate a return label", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}, "item_sku": {"type": "string"}}, "required": ["order_id", "reason"]}}}]

RESPONSE:
{"name": "initiate_return", "arguments": {"order_id": "ORD-70404", "item_sku": "94-248", "reason": "refund"}}
====================================================================================================
prompt: Where's my Dyson? ORD-51302
response_type: tool_call
intent: order_status
sub_intent: status_check
tool schema: [{"type": "function", "function": {"name": "get_order_status", "description": "Fetch live order status and tracking info", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "user_id": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
{"name": "get_order_status", "arguments": {"order_id": "ORD-51302"}}
====================================================================================================
prompt: Hey, what's up with my order for the Fluke 117? My order ID is ORD-64695.
response_type: tool_call
intent: order_status
sub_intent: status_check
tool schema: [{"type": "function", "function": {"name": "get_order_status", "description": "Fetch live order status and tracking info", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "user_id": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
{"name": "get_order_status", "arguments": {"order_id": "ORD-64695"}}
====================================================================================================
prompt: I am currently reviewing my cart and would like to make some adjustments. Specifically, I am interested in increasing the quantity of the Mamaearth Onion Shampoo from one unit to two. Could you please confirm if there are any current promotions or discounts applicable to this product if I purchase multiple units?
response_type: tool_call
intent: cart_management
sub_intent: add_item
tool schema: [{"type": "function", "function": {"name": "add_to_cart", "description": "Add an item to the cart", "parameters": {"type": "object", "properties": {"sku": {"type": "string"}, "qty": {"type": "integer"}}, "required": ["sku"]}}}, {"type": "function", "function": {"name": "update_cart_qty", "description": "Update item quantity in cart", "parameters": {"type": "object", "properties": {"sku": {"type": "string"}, "qty": {"type": "integer"}}, "required": ["sku", "qty"]}}}]

RESPONSE:
{"name": "add_to_cart", "arguments": {"sku": "Mamaearth Onion Shampoo", "qty": 2}}
====================================================================================================
prompt: Hey, I got my Mamaearth Onion Shampoo, order ORD-64566, but it looks like it leaked a bit in transit. Can I get a refund or maybe a replacement?
response_type: tool_call
intent: return_refund
sub_intent: refund_timeline
tool schema: [{"type": "function", "function": {"name": "initiate_return", "description": "Initiate a return and generate a return label", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "reason": {"type": "string"}, "item_sku": {"type": "string"}}, "required": ["order_id", "reason"]}}}]

RESPONSE:
{"name": "initiate_return", "arguments": {"order_id": "ORD-64566", "reason": "Damaged in transit", "item_sku": "Mamaearth Onion Shampoo"}}
====================================================================================================
prompt: I was wondering if you could tell me the status of my order for the Wonderchef Nutri-Blend Mixer, order ID ORD-74312?
response_type: tool_call
intent: order_status
sub_intent: eta_query
tool schema: [{"type": "function", "function": {"name": "get_order_status", "description": "Fetch live order status and tracking info", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "user_id": {"type": "string"}}, "required": ["order_id"]}}}]

RESPONSE:
{"name": "get_order_status", "arguments": {"order_id": "ORD-74312"}}
====================================================================================================
prompt: Hey, I ordered the MuscleBlaze Whey Protein (ORD-73402) but my payment failed. Can you help me out?
response_type: tool_call
intent: payment_issues
sub_intent: payment_method
tool schema: [{"type": "function", "function": {"name": "log_payment_dispute", "description": "Log a payment dispute and escalate to billing team", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "issue_type": {"type": "string", "enum": ["double_charge", "failed_payment", "wrong_amount", "unauthorized"]}, "amount": {"type": "number"}}, "required": ["order_id", "issue_type"]}}}]

RESPONSE:
{"name": "log_payment_dispute", "arguments": {"order_id": "ORD-73402", "issue_type": "failed_payment"}}
====================================================================================================
prompt: Hey, I'm looking at that Paws India cat scratching post, the one for around ₹999. Can I talk to someone about it?
response_type: mixed
intent: human_handoff
sub_intent: urgent_escalation
tool schema: [{"type": "function", "function": {"name": "escalate_to_agent", "description": "Transfer conversation to a live human agent", "parameters": {"type": "object", "properties": {"reason": {"type": "string"}, "priority": {"type": "string", "enum": ["low", "medium", "high", "urgent"]}, "context_summary": {"type": "string"}}, "required": ["reason", "priority"]}}}]

RESPONSE:
{"name": "escalate_to_agent", "arguments": {"query": "Paws India cat scratching post, around ₹999"}}
I'm connecting you with a customer service agent who can help you with your query about the Paws India cat scratching post.
====================================================================================================
prompt: Hey, I want to change the delivery address for my recent order of the WOW Skin Science Vitamin C Serum. Can you help me with that?
response_type: tool_call
intent: account_management
sub_intent: change_email
tool schema: [{"type": "function", "function": {"name": "update_account", "description": "Update user account details", "parameters": {"type": "object", "properties": {"user_id": {"type": "string"}, "field": {"type": "string", "enum": ["shipping_address", "email", "phone", "password"]}, "value": {"type": "string"}}, "required": ["user_id", "field", "value"]}}}]

RESPONSE:
{"name": "update_account", "arguments": {"user_id": "current", "field": "shipping_address", "value": "new_address_for_WOW_Skin_Science_Vitamin_C_Serum_order"}}
====================================================================================================
prompt: Hey there, I'm looking for the book Atomic Habits, do you have it in stock? And ideally, I'm hoping to spend under ₹999 if possible.
response_type: tool_call
intent: product_search
sub_intent: keyword_search
tool schema: [{"type": "function", "function": {"name": "search_products", "description": "Search the product catalog with filters", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "category": {"type": "string"}, "max_price": {"type": "number"}, "filters": {"type": "object"}}, "required": ["query"]}}}]

RESPONSE:
{"name": "search_products", "arguments": {"query": "Atomic Habits", "category": "Books", "max_price": 999}}
====================================================================================================

In [ ]:
!pip install -q -U transformers accelerate bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 60.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 13.3 MB/s eta 0:00:00

In [14]:
!pip install -U bitsandbytes>=0.46.1

In [15]:
!pip install -U bitsandbytes>=0.46.1

In [16]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto",
)

model.eval()

print("Model loaded successfully!")

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Model loaded successfully!

In [21]:
sample = no_detected_tool.iloc[0]

prompt = f"""
You are auditing an e-commerce customer support dataset.

Analyze the assistant's actual behavior based ONLY on the user prompt
and the reference response.

User prompt:
{sample["prompt"]}

Reference response:
{sample["response"]}

Classify the behavior into exactly one of these labels:

TOOL_CALL
DIRECT_ANSWER
CLARIFICATION
HUMAN_ESCALATION
MIXED
OTHER

Also identify whether the assistant actually called a tool.

Return ONLY valid JSON in this format:

{{
  "behavior": "...",
  "tool_called": true,
  "tool_name": "..."
}}

If no tool was called, use:
"tool_called": false
"tool_name": null
"""

messages = [
    {"role": "system", "content": "You are a precise dataset auditor. Return JSON only."},
    {"role": "user", "content": prompt}
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(text, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.0,
        do_sample=False,
    )

result = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print("=" * 100)
print(f"result \n {result}")
print("=" * 100)
print(f"prompt \n {sample["prompt"]}")
print("=" * 100)
print(f"response: \n {sample["response"]}")

====================================================================================================
result
 {
  "behavior": "DIRECT_ANSWER",
  "tool_called": false,
  "tool_name": null
}
====================================================================================================
prompt
 help me see in which situations cani ask to be refunded
====================================================================================================
response:
 Assuredly! I understand that you are seeking information about the situations in which you can request a refund. Let me provide you with a clear breakdown:

1. **Product/Service Defect:** If you find that the product or service you have purchased is defective or does not meet the stated description, you are usually eligible for a refund.
2. **Cancellation within Grace Period:** If you change your mind and decide to cancel your purchase within the specified grace period, you should be able to receive a refund.
3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or that appear unfamiliar, we will investigate and assist you in resolving the issue.
4. **Event Cancellation:** If you have purchased tickets for an event that gets canceled and is not rescheduled, you would typically be eligible for a refund.
5. **Duplicate Charges:** If you discover that you have been charged multiple times for the same item or service, please notify us so that we can rectify the situation promptly.
6. **Non-receipt of Goods:** If you have not received your ordered product within the expected delivery time frame, you may qualify for a refund.

Please keep in mind that refund policies can vary depending on the vendor or service provider. It is always recommended to consult their terms and conditions or directly reach out to them for a comprehensive understanding of their specific policies. If you have any specific concerns or questions related to an order or refund, please provide me with the necessary details, such as the ORD-83197857, and I'll be more than happy to assist you further. Your satisfaction is our top priority.

Let me know if there's anything else I can help you with!

In [23]:
def detecte_semantic(sample):
    prompt = f"""
    You are auditing an e-commerce customer support dataset.

    Analyze the assistant's actual behavior based ONLY on the user prompt
    and the reference response.

    User prompt:
    {sample["prompt"]}

    Reference response:
    {sample["response"]}

    Classify the behavior into exactly one of these labels:

    TOOL_CALL
    DIRECT_ANSWER
    CLARIFICATION
    HUMAN_ESCALATION
    MIXED
    OTHER

    Also identify whether the assistant actually called a tool.

    Return ONLY valid JSON in this format:

    {{
      "behavior": "...",
      "tool_called": true,
      "tool_name": "..."
    }}

    If no tool was called, use:
    "tool_called": false
    "tool_name": null
    """

    messages = [
        {"role": "system", "content": "You are a precise dataset auditor. Return JSON only."},
        {"role": "user", "content": prompt}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.0,
            do_sample=False,
        )

    result = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    return result

In [28]:
import json

results = []
sampled = no_detected_tool.sample(n=100, random_state=42)

for i, (_, sample) in enumerate(sampled.iterrows(), start=1):

    raw_result_str = detecte_semantic(sample)
    parsed_result_dict = json.loads(raw_result_str)
    results.append({
        "prompt": sample["prompt"],
        "response": sample["response"],
        **parsed_result_dict
    })

    if i % 10 == 0:
        print(f"Processed {i}/100 samples")

Processed 10/100 samples
Processed 20/100 samples
Processed 30/100 samples
Processed 40/100 samples
Processed 50/100 samples
Processed 60/100 samples
Processed 70/100 samples
Processed 80/100 samples
Processed 90/100 samples
Processed 100/100 samples

In [29]:
results_df = pd.DataFrame(results)

results_df.head(30)

,prompt,response,behavior,tool_called,tool_name
0,I have to add an article to order ORD-20202604...,We've received your message to us with your re...,CLARIFICATION,False,None
1,I can't seed your refund policy,I can sense that you're having trouble accessi...,DIRECT_ANSWER,False,None
2,can i check in which situations can i request ...,I'll do my best! I understand that you would l...,DIRECT_ANSWER,False,None
3,where can I cancel purchase ORD-36406053?,I've picked up that you're looking for informa...,DIRECT_ANSWER,False,None
4,"I got to make a fuckingh payment, how can I do...",My apologies for any frustration caused by the...,DIRECT_ANSWER,False,None
5,i want assistance adding a product to the basket,I'm happy to help! I'm here to help you add a ...,DIRECT_ANSWER,False,None
6,i bought an item but i do not want it I'd like...,I'm genuinely sorry to hear that you no longer...,DIRECT_ANSWER,False,None
7,"I want to cancel a fucking item, how to do it?",My apologies for any inconvenience you've expe...,DIRECT_ANSWER,False,None
8,i can no longer afford purchase ORD-93583837,I truly understand your situation and apologiz...,DIRECT_ANSWER,False,None
9,want help to cancel purchase ORD-64791659,I've got that you're seeking assistance with c...,DIRECT_ANSWER,False,None
10,i can no longer pay for order ORD-77670896,I can see that you're facing difficulties with...,HUMAN_ESCALATION,False,None
11,I have to modify my ufcking order before you s...,I genuinely apologize for any frustration caus...,DIRECT_ANSWER,False,None
12,i want hlp to cancel a fucking order,I sincerely apologize for any frustration or i...,CLARIFICATION,False,None
13,how do I add itmes to the cart?,Of course! I'm here to help you with adding it...,DIRECT_ANSWER,False,None
14,i bought an item but i chose a wrong size i go...,I genuinely apologize for any frustration caus...,DIRECT_ANSWER,False,None
15,i purchased an fucking product but i chose a w...,I deeply apologize for any inconvenience cause...,DIRECT_ANSWER,False,None
16,what do I need to do to find my invoice #00108?,I appreciate your inquiry about the process to...,HUMAN_ESCALATION,False,None
17,help to check in which cases can I request my ...,I'm on it! It's so important to have a clear u...,DIRECT_ANSWER,False,None
18,"I need to add a fucking item to the basket, he...",I deeply apologize for any frustration you may...,DIRECT_ANSWER,False,None
19,tell me more about correcting the delivery add...,I'll do my best! If you need assistance with c...,DIRECT_ANSWER,False,None
20,i have to see in what cases can i ask for reim...,Positively! I understand your need to gain cla...,DIRECT_ANSWER,False,None
21,"I want to add a item to the cart, help me",Assuredly! I'm here to assist you with adding ...,DIRECT_ANSWER,False,None
22,i got to add fucking items to the cart can i g...,Please know that I'm sorry for any frustration...,DIRECT_ANSWER,False,None
23,I'd like to pay how could i do it,I'm here to assist you with making a payment. ...,DIRECT_ANSWER,False,None
24,wanna cange an item of order ORD-25394501 how ...,I appreciate your need to change an item in yo...,HUMAN_ESCALATION,False,None
25,help to see in what cases can I request to be ...,I appreciate your request for assistance in un...,DIRECT_ANSWER,False,None
26,want help to check in what cases can i request...,I'll take care of it! I understand your desire...,DIRECT_ANSWER,False,None
27,I need help cancelnig purchase ORD-17385875,I truly understand the urgency of canceling yo...,DIRECT_ANSWER,False,None
28,see invoices from Jessica Taylor,I appreciate your request for accessing the in...,CLARIFICATION,False,None
29,I need assistance locating my fucking bill fro...,I'll take care of it! I'm here to assist you i...,CLARIFICATION,False,None

In [30]:
results_df["behavior"].value_counts()

behavior
DIRECT_ANSWER       72
CLARIFICATION       22
HUMAN_ESCALATION     6
Name: count, dtype: int64

In [32]:
print(results_df.iloc[24])

prompt         wanna cange an item of order ORD-25394501 how ...
response       I appreciate your need to change an item in yo...
behavior                                        HUMAN_ESCALATION
tool_called                                                False
tool_name                                                   None
Name: 24, dtype: object